// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localAccount,
    metadataCopies,
    localMutations,
    mutationQueue,
    mutationTarget,
    localRecordingFiles,
    recordingJournals,
    importJobs,
    importItems,
    syncCursors,
    localAccountNoUpdate,
    localAccountNoDelete,
    mutationRequestImmutable,
    cursorNoRewind,
    mutationWireRequests,
    mutationWireRequestImmutable,
  ];
  late final Shape0 localAccount = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_account',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 metadataCopies = Shape1(
    source: i0.VersionedTable(
      entityName: 'metadata_copies',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(entity_type, entity_id)',
        'CHECK((server_revision = 0 AND server_payload IS NULL)OR(server_revision > 0 AND server_payload IS NOT NULL))',
        'CHECK(tombstone = 0 OR server_revision > 0)',
      ],
      columns: [
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localMutations = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_mutations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(entity_type, entity_id)REFERENCES metadata_copies(entity_type, entity_id)',
        'CHECK((base_revision = 0 AND base_payload IS NULL)OR(base_revision > 0 AND base_payload IS NOT NULL))',
      ],
      columns: [
        _column_12,
        _column_4,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_3,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index mutationQueue = i1.Index(
    'mutation_queue',
    'CREATE INDEX mutation_queue ON local_mutations (queue_state, next_attempt_at, created_at, op_id)',
  );
  final i1.Index mutationTarget = i1.Index(
    'mutation_target',
    'CREATE INDEX mutation_target ON local_mutations (entity_type, entity_id, created_at)',
  );
  late final Shape3 localRecordingFiles = Shape3(
    source: i0.VersionedTable(
      entityName: 'local_recording_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(user_id, recording_id)',
        'CHECK(relative_path = \'audio/\' || recording_id || \'.m4a\' OR relative_path = \'pending/\' || recording_id || \'.m4a.part\')',
        'CHECK(local_state NOT IN (\'INPUT_PENDING\', \'SAVED\') OR(sha256 IS NOT NULL AND size_bytes IS NOT NULL AND verified_at IS NOT NULL AND relative_path = \'audio/\' || recording_id || \'.m4a\'))',
      ],
      columns: [
        _column_24,
        _column_4,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 recordingJournals = Shape4(
    source: i0.VersionedTable(
      entityName: 'recording_journals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(user_id, recording_id)REFERENCES local_recording_files(user_id, recording_id)',
        'CHECK(pending_path = \'pending/\' || recording_id || \'.m4a.part\')',
        'CHECK(final_path = \'audio/\' || recording_id || \'.m4a\')',
      ],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 importJobs = Shape5(
    source: i0.VersionedTable(
      entityName: 'import_jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(archive_path = \'imports/\' || import_job_id || \'.zip\')',
        'CHECK(status <> \'COMPLETED\' OR completed_items = total_items)',
      ],
      columns: [
        _column_39,
        _column_4,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_3,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 importItems = Shape6(
    source: i0.VersionedTable(
      entityName: 'import_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(import_job_id, ordinal)'],
      columns: [
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 syncCursors = Shape7(
    source: i0.VersionedTable(
      entityName: 'sync_cursors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(baseline_complete = 0 OR last_change_seq IS NOT NULL)',
      ],
      columns: [
        _column_0,
        _column_4,
        _column_52,
        _column_53,
        _column_54,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger localAccountNoUpdate = i1.Trigger(
    'CREATE TRIGGER local_account_no_update BEFORE UPDATE ON local_account BEGIN SELECT RAISE (ABORT, \'Local database ownership is immutable\');END',
    'local_account_no_update',
  );
  final i1.Trigger localAccountNoDelete = i1.Trigger(
    'CREATE TRIGGER local_account_no_delete BEFORE DELETE ON local_account BEGIN SELECT RAISE (ABORT, \'Local database ownership cannot be removed\');END',
    'local_account_no_delete',
  );
  final i1.Trigger mutationRequestImmutable = i1.Trigger(
    'CREATE TRIGGER mutation_request_immutable BEFORE UPDATE ON local_mutations WHEN NEW.op_id <> OLD.op_id OR NEW.user_id <> OLD.user_id OR NEW.entity_type <> OLD.entity_type OR NEW.entity_id <> OLD.entity_id OR NEW.operation <> OLD.operation OR NEW.base_revision <> OLD.base_revision OR NEW.base_payload IS NOT OLD.base_payload OR NEW.payload <> OLD.payload OR NEW.request_hash <> OLD.request_hash OR NEW.created_at <> OLD.created_at OR NEW.attempt_count < OLD.attempt_count BEGIN SELECT RAISE (ABORT, \'Mutation identity and request must survive retries unchanged\');END',
    'mutation_request_immutable',
  );
  final i1.Trigger cursorNoRewind = i1.Trigger(
    'CREATE TRIGGER cursor_no_rewind BEFORE UPDATE ON sync_cursors WHEN NEW.user_id <> OLD.user_id OR(OLD.last_change_seq IS NOT NULL AND(NEW.last_change_seq IS NULL OR NEW.last_change_seq < OLD.last_change_seq))BEGIN SELECT RAISE (ABORT, \'Do not discard an acknowledged cursor\');END',
    'cursor_no_rewind',
  );
  late final Shape8 mutationWireRequests = Shape8(
    source: i0.VersionedTable(
      entityName: 'mutation_wire_requests',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger mutationWireRequestImmutable = i1.Trigger(
    'CREATE TRIGGER mutation_wire_request_immutable BEFORE UPDATE ON mutation_wire_requests BEGIN SELECT RAISE (ABORT, \'Frozen HTTP requests must survive retries unchanged\');END',
    'mutation_wire_request_immutable',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get singleton =>
      columnsByName['singleton']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get environment =>
      columnsByName['environment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'singleton',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY CHECK (singleton = 1)',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE CHECK (length(user_id) = 36)',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'environment',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (environment IN (\'dev\', \'staging\', \'prod\'))',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serverRevision =>
      columnsByName['server_revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get serverPayload =>
      columnsByName['server_payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localPayload =>
      columnsByName['local_payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get tombstone =>
      columnsByName['tombstone']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES local_account(user_id)',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (entity_type IN (\'SONG\', \'RECORDING\', \'PLAYLIST\', \'PLAYLIST_ITEM\', \'TAG\', \'RECORDING_TAG\', \'RECORDING_CONDITION\', \'RECORDING_FILE_SPEC\', \'RECORDING_ASSET\', \'SONG_CLOUD_SELECTION\', \'PIN_SLOT\', \'USER_ENTITLEMENT\', \'DELETION_LEDGER\'))',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(entity_id) = 36)',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'server_revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (server_revision >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_payload',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (server_payload IS NULL OR(json_valid(server_payload) AND json_type(server_payload) = \'object\'))',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_payload',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (local_payload IS NULL OR(json_valid(local_payload) AND json_type(local_payload) = \'object\'))',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tombstone',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (tombstone IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get opId =>
      columnsByName['op_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityType =>
      columnsByName['entity_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entityId =>
      columnsByName['entity_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get operation =>
      columnsByName['operation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get baseRevision =>
      columnsByName['base_revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get basePayload =>
      columnsByName['base_payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get requestHash =>
      columnsByName['request_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get queueState =>
      columnsByName['queue_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get attemptCount =>
      columnsByName['attempt_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextAttemptAt =>
      columnsByName['next_attempt_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get serverResponse =>
      columnsByName['server_response']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'op_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY CHECK (length(op_id) = 36)',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entity_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operation',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (operation IN (\'CREATE\', \'PATCH\', \'TRASH\', \'RESTORE\', \'PURGE\'))',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'base_revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (base_revision >= 0)',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'base_payload',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (base_payload IS NULL OR(json_valid(base_payload) AND json_type(base_payload) = \'object\'))',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (json_valid(payload) AND json_type(payload) = \'object\')',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'request_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(request_hash) = 64 AND request_hash NOT GLOB \'*[^0-9a-f]*\')',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'queue_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'PENDING\' CHECK (queue_state IN (\'PENDING\', \'SENDING\', \'RETRY\', \'CONFLICT\', \'ACKED\', \'FAILED\'))',
      defaultValue: const i1.CustomExpression('\'PENDING\''),
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempt_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (attempt_count >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_response',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (server_response IS NULL OR(json_valid(server_response) AND json_type(server_response) = \'object\'))',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get recordingId =>
      columnsByName['recording_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sizeBytes =>
      columnsByName['size_bytes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get localState =>
      columnsByName['local_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cleanupFence =>
      columnsByName['cleanup_fence']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get verifiedAt =>
      columnsByName['verified_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recording_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL PRIMARY KEY CHECK (length(recording_id) = 36)',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sha256',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (sha256 IS NULL OR(length(sha256) = 64 AND sha256 NOT GLOB \'*[^0-9a-f]*\'))',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size_bytes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (size_bytes IS NULL OR size_bytes BETWEEN 1 AND 6291456)',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (local_state IN (\'CAPTURING\', \'INPUT_PENDING\', \'SAVED\', \'INTERRUPTED\', \'CORRUPT\', \'MISSING\'))',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cleanup_fence',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (cleanup_fence >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'verified_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get recordingId =>
      columnsByName['recording_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get operationId =>
      columnsByName['operation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pendingPath =>
      columnsByName['pending_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get finalPath =>
      columnsByName['final_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phase =>
      columnsByName['phase']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get recoveryPayload =>
      columnsByName['recovery_payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get revision =>
      columnsByName['revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recording_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE CHECK (length(operation_id) = 36)',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pending_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'final_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phase',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (phase IN (\'PREPARING\', \'CAPTURING\', \'FINALIZING\', \'VERIFIED\', \'COMMITTED\', \'FAILED\'))',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'recovery_payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (json_valid(recovery_payload) AND json_type(recovery_payload) = \'object\')',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (revision > 0)',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get importJobId =>
      columnsByName['import_job_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceUserId =>
      columnsByName['source_user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get archivePath =>
      columnsByName['archive_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get manifestHash =>
      columnsByName['manifest_hash']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalItems =>
      columnsByName['total_items']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedItems =>
      columnsByName['completed_items']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get errorCode =>
      columnsByName['error_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'import_job_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL PRIMARY KEY CHECK (length(import_job_id) = 36)',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (source_user_id = user_id)',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'archive_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'manifest_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(manifest_hash) = 64 AND manifest_hash NOT GLOB \'*[^0-9a-f]*\')',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'PENDING\' CHECK (status IN (\'PENDING\', \'RUNNING\', \'PAUSED\', \'COMPLETED\', \'FAILED\'))',
      defaultValue: const i1.CustomExpression('\'PENDING\''),
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_items',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (total_items >= 0)',
    );
i1.GeneratedColumn<int> _column_45(
  String aliasedName,
) => i1.GeneratedColumn<int>(
  'completed_items',
  aliasedName,
  false,
  type: i1.DriftSqlType.int,
  $customConstraints:
      'NOT NULL DEFAULT 0 CHECK (completed_items BETWEEN 0 AND total_items)',
  defaultValue: const i1.CustomExpression('0'),
);
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'error_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get importJobId =>
      columnsByName['import_job_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get resourceId =>
      columnsByName['resource_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resultPayload =>
      columnsByName['result_payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'import_job_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES import_jobs(import_job_id)',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (ordinal > 0)',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'resource_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(resource_id) = 36)',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'PENDING\' CHECK (status IN (\'PENDING\', \'APPLIED\', \'SKIPPED\', \'CONFLICT\', \'FAILED\'))',
      defaultValue: const i1.CustomExpression('\'PENDING\''),
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'result_payload',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (result_payload IS NULL OR(json_valid(result_payload) AND json_type(result_payload) = \'object\'))',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get singleton =>
      columnsByName['singleton']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastChangeSeq =>
      columnsByName['last_change_seq']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get baselineComplete =>
      columnsByName['baseline_complete']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get snapshotResume =>
      columnsByName['snapshot_resume']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_change_seq',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'CHECK (last_change_seq IS NULL OR last_change_seq >= 0)',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'baseline_complete',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (baseline_complete IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'snapshot_resume',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (snapshot_resume IS NULL OR(json_valid(snapshot_resume) AND json_type(snapshot_resume) = \'object\'))',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get opId =>
      columnsByName['op_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contractVersion =>
      columnsByName['contract_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get httpMethod =>
      columnsByName['http_method']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bodyJson =>
      columnsByName['body_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wireHash =>
      columnsByName['wire_hash']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'op_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL PRIMARY KEY REFERENCES local_mutations(op_id)',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contract_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'http_method',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (http_method IN (\'POST\', \'PATCH\'))',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'body_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (json_valid(body_json) AND json_type(body_json) = \'object\')',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'wire_hash',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(wire_hash) = 64 AND wire_hash NOT GLOB \'*[^0-9a-f]*\')',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localAccount,
    metadataCopies,
    localMutations,
    mutationQueue,
    mutationTarget,
    localRecordingFiles,
    recordingJournals,
    importJobs,
    importItems,
    syncCursors,
    localAccountNoUpdate,
    localAccountNoDelete,
    mutationRequestImmutable,
    cursorNoRewind,
    mutationWireRequests,
    mutationWireRequestImmutable,
    mutationRetryControls,
    mutationRetryBudgetMonotonic,
  ];
  late final Shape0 localAccount = Shape0(
    source: i0.VersionedTable(
      entityName: 'local_account',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 metadataCopies = Shape1(
    source: i0.VersionedTable(
      entityName: 'metadata_copies',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(entity_type, entity_id)',
        'CHECK((server_revision = 0 AND server_payload IS NULL)OR(server_revision > 0 AND server_payload IS NOT NULL))',
        'CHECK(tombstone = 0 OR server_revision > 0)',
      ],
      columns: [
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 localMutations = Shape2(
    source: i0.VersionedTable(
      entityName: 'local_mutations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(entity_type, entity_id)REFERENCES metadata_copies(entity_type, entity_id)',
        'CHECK((base_revision = 0 AND base_payload IS NULL)OR(base_revision > 0 AND base_payload IS NOT NULL))',
      ],
      columns: [
        _column_12,
        _column_4,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_3,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index mutationQueue = i1.Index(
    'mutation_queue',
    'CREATE INDEX mutation_queue ON local_mutations (queue_state, next_attempt_at, created_at, op_id)',
  );
  final i1.Index mutationTarget = i1.Index(
    'mutation_target',
    'CREATE INDEX mutation_target ON local_mutations (entity_type, entity_id, created_at)',
  );
  late final Shape3 localRecordingFiles = Shape3(
    source: i0.VersionedTable(
      entityName: 'local_recording_files',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'UNIQUE(user_id, recording_id)',
        'CHECK(relative_path = \'audio/\' || recording_id || \'.m4a\' OR relative_path = \'pending/\' || recording_id || \'.m4a.part\')',
        'CHECK(local_state NOT IN (\'INPUT_PENDING\', \'SAVED\') OR(sha256 IS NOT NULL AND size_bytes IS NOT NULL AND verified_at IS NOT NULL AND relative_path = \'audio/\' || recording_id || \'.m4a\'))',
      ],
      columns: [
        _column_24,
        _column_4,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 recordingJournals = Shape4(
    source: i0.VersionedTable(
      entityName: 'recording_journals',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(user_id, recording_id)REFERENCES local_recording_files(user_id, recording_id)',
        'CHECK(pending_path = \'pending/\' || recording_id || \'.m4a.part\')',
        'CHECK(final_path = \'audio/\' || recording_id || \'.m4a\')',
      ],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 importJobs = Shape5(
    source: i0.VersionedTable(
      entityName: 'import_jobs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(archive_path = \'imports/\' || import_job_id || \'.zip\')',
        'CHECK(status <> \'COMPLETED\' OR completed_items = total_items)',
      ],
      columns: [
        _column_39,
        _column_4,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_3,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 importItems = Shape6(
    source: i0.VersionedTable(
      entityName: 'import_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(import_job_id, ordinal)'],
      columns: [
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 syncCursors = Shape7(
    source: i0.VersionedTable(
      entityName: 'sync_cursors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(baseline_complete = 0 OR last_change_seq IS NOT NULL)',
      ],
      columns: [
        _column_0,
        _column_4,
        _column_52,
        _column_53,
        _column_54,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger localAccountNoUpdate = i1.Trigger(
    'CREATE TRIGGER local_account_no_update BEFORE UPDATE ON local_account BEGIN SELECT RAISE (ABORT, \'Local database ownership is immutable\');END',
    'local_account_no_update',
  );
  final i1.Trigger localAccountNoDelete = i1.Trigger(
    'CREATE TRIGGER local_account_no_delete BEFORE DELETE ON local_account BEGIN SELECT RAISE (ABORT, \'Local database ownership cannot be removed\');END',
    'local_account_no_delete',
  );
  final i1.Trigger mutationRequestImmutable = i1.Trigger(
    'CREATE TRIGGER mutation_request_immutable BEFORE UPDATE ON local_mutations WHEN NEW.op_id <> OLD.op_id OR NEW.user_id <> OLD.user_id OR NEW.entity_type <> OLD.entity_type OR NEW.entity_id <> OLD.entity_id OR NEW.operation <> OLD.operation OR NEW.base_revision <> OLD.base_revision OR NEW.base_payload IS NOT OLD.base_payload OR NEW.payload <> OLD.payload OR NEW.request_hash <> OLD.request_hash OR NEW.created_at <> OLD.created_at OR NEW.attempt_count < OLD.attempt_count BEGIN SELECT RAISE (ABORT, \'Mutation identity and request must survive retries unchanged\');END',
    'mutation_request_immutable',
  );
  final i1.Trigger cursorNoRewind = i1.Trigger(
    'CREATE TRIGGER cursor_no_rewind BEFORE UPDATE ON sync_cursors WHEN NEW.user_id <> OLD.user_id OR(OLD.last_change_seq IS NOT NULL AND(NEW.last_change_seq IS NULL OR NEW.last_change_seq < OLD.last_change_seq))BEGIN SELECT RAISE (ABORT, \'Do not discard an acknowledged cursor\');END',
    'cursor_no_rewind',
  );
  late final Shape8 mutationWireRequests = Shape8(
    source: i0.VersionedTable(
      entityName: 'mutation_wire_requests',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger mutationWireRequestImmutable = i1.Trigger(
    'CREATE TRIGGER mutation_wire_request_immutable BEFORE UPDATE ON mutation_wire_requests BEGIN SELECT RAISE (ABORT, \'Frozen HTTP requests must survive retries unchanged\');END',
    'mutation_wire_request_immutable',
  );
  late final Shape9 mutationRetryControls = Shape9(
    source: i0.VersionedTable(
      entityName: 'mutation_retry_controls',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_55, _column_61, _column_62, _column_63],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Trigger mutationRetryBudgetMonotonic = i1.Trigger(
    'CREATE TRIGGER mutation_retry_budget_monotonic BEFORE UPDATE ON mutation_retry_controls WHEN NEW.op_id <> OLD.op_id OR(OLD.automatic_retries_claimed IS NULL AND NEW.automatic_retries_claimed IS NOT NULL)OR(OLD.automatic_retries_claimed IS NOT NULL AND NEW.automatic_retries_claimed IS NULL)OR NEW.automatic_retries_claimed < OLD.automatic_retries_claimed OR NEW.automatic_retries_claimed > OLD.automatic_retries_claimed + 1 BEGIN SELECT RAISE (ABORT, \'Automatic retry budget cannot be replenished\');END',
    'mutation_retry_budget_monotonic',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get opId =>
      columnsByName['op_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get automaticRetriesClaimed =>
      columnsByName['automatic_retries_claimed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get retryMode =>
      columnsByName['retry_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAttemptKind =>
      columnsByName['last_attempt_kind']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'automatic_retries_claimed',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'CHECK (automatic_retries_claimed IS NULL OR automatic_retries_claimed BETWEEN 0 AND 3)',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'retry_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (retry_mode IN (\'INITIAL\', \'AUTO\', \'MANUAL_REQUIRED\', \'MANUAL_READY\', \'BLOCKED\'))',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_attempt_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (last_attempt_kind IN (\'INITIAL\', \'AUTO\', \'MANUAL\', \'UNKNOWN\'))',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
