name: song_record
description: "개인 노래 기록 Android 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: 7.2.0
  kakao_flutter_sdk_user: 2.0.1
  flutter_secure_storage: 10.3.4
  cupertino_icons: ^1.0.8
  drift: 2.35.0
  sqlite3: 3.5.2
  path: ^1.9.1
  path_provider: ^2.1.6
  crypto: ^3.0.7
  unorm_dart: 0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: 2.35.0
  build_runner: ^2.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/verification/playback-tone.m4a
