package com.ksh321.songrecord.api.retention;
import java.time.*;import java.util.*;import java.util.concurrent.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import com.ksh321.songrecord.api.auth.*;import com.ksh321.songrecord.api.idempotency.IdempotentMutations;import com.ksh321.songrecord.api.jobs.JobQueue;import com.ksh321.songrecord.api.web.ApiException;
import static com.ksh321.songrecord.api.retention.RetentionCandidateDatabaseChecks.*;import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
/** Identical locked decisions and real pin API order on H2 and fully migrated InnoDB. */
public final class CleanupAuthorizationDatabaseChecks {
 public static void verify(JdbcTemplate db)throws Exception{
  UUID owner=account(db),dev=device(db,owner);db.update("INSERT INTO user_sync_state(user_id) VALUES(?)",bytes(owner));db.update("INSERT INTO user_entitlement(user_id,pinned_limit,quota_bytes) VALUES(?,10,1073741824)",bytes(owner));db.update("INSERT INTO storage_usage(user_id,used_bytes) VALUES(?,62914560)",bytes(owner));
  var access=mock(AccountAccess.class);var account=mock(AccountAccess.Account.class);var principal=new SessionService.Principal(owner,dev,UUID.randomUUID());when(access.authenticate("fixture",dev.toString())).thenReturn(account);when(access.revalidate(account)).thenReturn(principal);when(account.principal()).thenReturn(principal);
  var clock=new CleanupConfirmationDatabaseChecks.MutableClock();var manager=new DataSourceTransactionManager(db.getDataSource());var mutations=new IdempotentMutations(db,access,manager,clock);var confirmations=new CleanupConfirmations(db,access,mutations,clock);var queue=new JobQueue(db,access,manager,clock,Duration.ofMinutes(2),5);var authorizer=new CleanupAuthorizations(db,manager,queue,clock);var pins=new PinSlots(db,access,mutations);
  UUID id=seed(db,owner,dev),token=confirmed(confirmations,owner,dev,id);
  assertThat(authorizer.authorize(owner,token)).isEqualTo("DELETING");assertThat(authorizer.authorize(owner,token)).isEqualTo("DELETING");assertThat(state(db,owner,id)).isEqualTo("DELETING");assertThat(db.queryForObject("SELECT COUNT(*) FROM job WHERE user_id=? AND aggregate_id=? AND type='ASSET_DELETE'",Long.class,bytes(owner),bytes(token))).isEqualTo(1);assertThat(db.queryForObject("SELECT COUNT(*) FROM cloud_hold WHERE user_id=? AND recording_id=?",Long.class,bytes(owner),bytes(id))).isZero();assertThat(db.queryForObject("SELECT lifecycle_state FROM recording WHERE user_id=? AND id=?",String.class,bytes(owner),bytes(id))).isEqualTo("ACTIVE");assertThat(db.queryForObject("SELECT COUNT(*) FROM change_log WHERE user_id=? AND entity_id=? AND entity_type='RECORDING_ASSET'",Long.class,bytes(owner),bytes(id))).isEqualTo(1);
  error(()->pins.reserve("fixture",dev.toString(),UUID.randomUUID().toString(),pin(id)),"FILE_CLEANUP_IN_PROGRESS");
  UUID earlier=seed(db,owner,dev),earlierToken=confirmed(confirmations,owner,dev,earlier);assertThat(pins.reserve("fixture",dev.toString(),UUID.randomUUID().toString(),pin(earlier)).status()).isEqualTo(201);assertThat(authorizer.authorize(owner,earlierToken)).isEqualTo("CANCELLED");assertThat(state(db,owner,earlier)).isEqualTo("STORED");assertNoJob(db,earlierToken);assertThat(db.queryForObject("SELECT COUNT(*) FROM cloud_hold WHERE recording_id=?",Long.class,bytes(earlier))).isEqualTo(2);
  UUID role=seed(db,owner,dev),roleToken=confirmed(confirmations,owner,dev,role),song=song(db,owner);db.update("UPDATE recording SET song_id=? WHERE id=?",bytes(song),bytes(role));assertThat(authorizer.authorize(owner,roleToken)).isEqualTo("CANCELLED");assertNoJob(db,roleToken);
  UUID held=seed(db,owner,dev),heldToken=confirmed(confirmations,owner,dev,held);db.update("INSERT INTO cloud_hold(id,user_id,recording_id,reason) VALUES(?,?,?,'PENDING_REPLACEMENT')",bytes(UUID.randomUUID()),bytes(owner),bytes(held));assertThat(authorizer.authorize(owner,heldToken)).isEqualTo("CANCELLED");assertNoJob(db,heldToken);
  UUID expired=seed(db,owner,dev),expiredToken=confirmed(confirmations,owner,dev,expired);clock.at=clock.at.plusSeconds(900);assertThat(authorizer.authorize(owner,expiredToken)).isEqualTo("EXPIRED");assertThat(state(db,owner,expired)).isEqualTo("STORED");assertNoJob(db,expiredToken);
  UUID changed=seed(db,owner,dev),changedToken=confirmed(confirmations,owner,dev,changed),generation=UUID.randomUUID();db.update("UPDATE recording_asset SET generation=?,object_key=?,cloud_revision=cloud_revision+1 WHERE recording_id=?",bytes(generation),new com.ksh321.songrecord.api.storage.StorageObjectKeys.Final(owner,changed,generation).value(),bytes(changed));assertThat(authorizer.authorize(owner,changedToken)).isEqualTo("CANCELLED");assertNoJob(db,changedToken);
  UUID rollback=seed(db,owner,dev),rollbackToken=confirmed(confirmations,owner,dev,rollback);var broken=mock(JobQueue.class);when(broken.enqueueOwnedMaintenance(any(),any(),any(),any(),anyString())).thenThrow(new IllegalStateException("fixture queue failure"));assertThatThrownBy(()->new CleanupAuthorizations(db,manager,broken,clock).authorize(owner,rollbackToken)).isInstanceOf(IllegalStateException.class);assertThat(state(db,owner,rollback)).isEqualTo("STORED");assertThat(db.queryForObject("SELECT state FROM cloud_cleanup WHERE id=?",String.class,bytes(rollbackToken))).isEqualTo("CONFIRMED");assertThat(db.queryForObject("SELECT COUNT(*) FROM cloud_hold WHERE recording_id=?",Long.class,bytes(rollback))).isEqualTo(2);assertNoJob(db,rollbackToken);
  UUID race=seed(db,owner,dev),raceToken=confirmed(confirmations,owner,dev,race);try(var pool=Executors.newFixedThreadPool(2)){var go=new CountDownLatch(1);var pinResult=pool.submit(()->{go.await();try{return Integer.toString(pins.reserve("fixture",dev.toString(),UUID.randomUUID().toString(),pin(race)).status());}catch(ApiException e){return e.code();}});var cleanupResult=pool.submit(()->{go.await();return authorizer.authorize(owner,raceToken);});go.countDown();String p=pinResult.get(30,TimeUnit.SECONDS),c=cleanupResult.get(30,TimeUnit.SECONDS);assertThat(List.of(p+"/"+c)).containsAnyOf("201/CANCELLED","FILE_CLEANUP_IN_PROGRESS/DELETING");}
  assertThat(db.queryForObject("SELECT used_bytes FROM storage_usage WHERE user_id=?",Long.class,bytes(owner))).isEqualTo(62914560);
 }
 static UUID seed(JdbcTemplate db,UUID owner,UUID dev){UUID id=recording(db,owner,dev,null,true,true,"VALIDATED");CleanupConfirmationDatabaseChecks.stored(db,owner,id,UUID.randomUUID());for(String reason:List.of("ORPHAN_KEEP","WAITING_LOCAL_CONFIRM"))db.update("INSERT INTO cloud_hold(id,user_id,recording_id,reason) VALUES(?,?,?,?)",bytes(UUID.randomUUID()),bytes(owner),bytes(id),reason);return id;}
 static UUID confirmed(CleanupConfirmations service,UUID owner,UUID dev,UUID id){var json=new tools.jackson.databind.json.JsonMapper();String reply=service.preview("fixture",dev.toString(),UUID.randomUUID().toString(),json.writeValueAsString(Map.of("recording_ids",List.of(id.toString())))).body();UUID token=UUID.fromString(json.readTree(reply).get("items").get(0).get("token").asText());service.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),CleanupConfirmationDatabaseChecks.confirm(token.toString(),dev,"LOCAL_VERIFIED","a".repeat(64),false));return token;}
 static String pin(UUID id){return "{\"recording_id\":\""+id+"\",\"entitlement_revision\":1}";}
 static String state(JdbcTemplate db,UUID owner,UUID id){return db.queryForObject("SELECT cloud_state FROM recording_asset WHERE user_id=? AND recording_id=?",String.class,bytes(owner),bytes(id));}
 static void assertNoJob(JdbcTemplate db,UUID token){assertThat(db.queryForObject("SELECT COUNT(*) FROM job WHERE aggregate_id=?",Long.class,bytes(token))).isZero();}
 static void error(Runnable r,String code){assertThatThrownBy(r::run).isInstanceOfSatisfying(ApiException.class,e->assertThat(e.code()).isEqualTo(code));}
}
