package com.ksh321.songrecord.api.retention;
import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import com.ksh321.songrecord.api.auth.*;import com.ksh321.songrecord.api.idempotency.*;import com.ksh321.songrecord.api.web.ApiException;import tools.jackson.databind.json.JsonMapper;
import static com.ksh321.songrecord.api.retention.RetentionCandidateDatabaseChecks.*;import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
public final class CleanupConfirmationDatabaseChecks {
 static final JsonMapper JSON=new JsonMapper();
 public static void verify(JdbcTemplate db){
  UUID owner=account(db),dev=device(db,owner),id=recording(db,owner,dev,null,true,true,"VALIDATED"),gen=UUID.randomUUID();db.update("INSERT INTO user_sync_state(user_id) VALUES(?)",bytes(owner));db.update("INSERT INTO storage_usage(user_id,used_bytes) VALUES(?,6291456)",bytes(owner));stored(db,owner,id,gen);
  var access=mock(AccountAccess.class);var account=mock(AccountAccess.Account.class);var principal=new SessionService.Principal(owner,dev,UUID.randomUUID());when(access.authenticate("fixture",dev.toString())).thenReturn(account);when(access.revalidate(account)).thenReturn(principal);when(account.principal()).thenReturn(principal);
  var clock=new MutableClock();var manager=new DataSourceTransactionManager(db.getDataSource());var service=new CleanupConfirmations(db,access,new IdempotentMutations(db,access,manager,clock),clock);String body=JSON.writeValueAsString(Map.of("recording_ids",List.of(id.toString()))),op=UUID.randomUUID().toString();var reply=service.preview("fixture",dev.toString(),op,body);
  assertThat(service.preview("fixture",dev.toString(),op,body)).isEqualTo(reply);String token=JSON.readTree(reply.body()).get("items").get(0).get("token").asText();assertThat(JSON.readTree(service.preview("fixture",dev.toString(),UUID.randomUUID().toString(),body).body()).get("items").get(0).get("token").asText()).isEqualTo(token);
  String confirm=confirm(token,dev,"LOCAL_VERIFIED","a".repeat(64),false);code(()->service.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),confirm.replace("a".repeat(64),"b".repeat(64))),"CLEANUP_OBJECT_CHANGED");
  var foreign=mock(AccountAccess.Account.class);UUID other=account(db),od=device(db,other);var foreignPrincipal=new SessionService.Principal(other,od,UUID.randomUUID());db.update("INSERT INTO user_sync_state(user_id) VALUES(?)",bytes(other));when(access.authenticate("other",od.toString())).thenReturn(foreign);when(access.revalidate(foreign)).thenReturn(foreignPrincipal);when(foreign.principal()).thenReturn(foreignPrincipal);code(()->service.confirm("other",od.toString(),UUID.randomUUID().toString(),confirm(token,od,"LOCAL_VERIFIED","a".repeat(64),false)),"CLEANUP_TOKEN_INVALID");
  clock.at=clock.at.plusSeconds(900);code(()->service.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),confirm),"CLEANUP_TOKEN_EXPIRED");
  String fresh=JSON.readTree(service.preview("fixture",dev.toString(),UUID.randomUUID().toString(),body).body()).get("items").get(0).get("token").asText();assertThat(fresh).isNotEqualTo(token);
  db.update("UPDATE recording_asset SET cloud_revision=cloud_revision+1 WHERE recording_id=?",bytes(id));code(()->service.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),confirm(fresh,dev,"LOCAL_VERIFIED","a".repeat(64),false)),"CLEANUP_OBJECT_CHANGED");
  String current=JSON.readTree(service.preview("fixture",dev.toString(),UUID.randomUUID().toString(),body).body()).get("items").get(0).get("token").asText();
  UUID nextGen=UUID.randomUUID();db.update("UPDATE recording_asset SET generation=?,object_key=?,cloud_revision=cloud_revision+1 WHERE recording_id=?",bytes(nextGen),new com.ksh321.songrecord.api.storage.StorageObjectKeys.Final(owner,id,nextGen).value(),bytes(id));code(()->service.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),confirm(current,dev,"LOCAL_VERIFIED","a".repeat(64),false)),"CLEANUP_OBJECT_CHANGED");
  String latest=JSON.readTree(service.preview("fixture",dev.toString(),UUID.randomUUID().toString(),body).body()).get("items").get(0).get("token").asText();
  code(()->service.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),confirm(latest,dev,"USER_CONFIRMED_LOSS","a".repeat(64),false)),"VALIDATION_FAILED");
  String confirmed=confirm(latest,dev,"LOCAL_VERIFIED","a".repeat(64),false);String confirmOp=UUID.randomUUID().toString();var acknowledged=service.confirm("fixture",dev.toString(),confirmOp,confirmed);assertThat(service.confirm("fixture",dev.toString(),confirmOp,confirmed)).isEqualTo(acknowledged);assertThat(service.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),confirmed)).isEqualTo(acknowledged);
  assertThat(db.queryForObject("SELECT state FROM cloud_cleanup WHERE id=?",String.class,bytes(UUID.fromString(latest)))).isEqualTo("CONFIRMED");assertThat(db.queryForObject("SELECT cloud_state FROM recording_asset WHERE recording_id=?",String.class,bytes(id))).isEqualTo("STORED");assertThat(db.queryForObject("SELECT used_bytes FROM storage_usage WHERE user_id=?",Long.class,bytes(owner))).isEqualTo(6291456);
 }
 static String confirm(String token,UUID device,String mode,String hash,boolean understands){var m=new LinkedHashMap<String,Object>();m.put("token",token);m.put("device_id",device.toString());m.put("mode",mode);m.put("sha256",hash);if(mode.equals("USER_CONFIRMED_LOSS"))m.put("understands_loss",understands);return JSON.writeValueAsString(m);}
 static void code(Runnable action,String expected){assertThatThrownBy(action::run).isInstanceOfSatisfying(ApiException.class,e->assertThat(e.code()).isEqualTo(expected));}
 static void stored(JdbcTemplate db,UUID owner,UUID id,UUID generation){db.update("INSERT INTO recording_asset(recording_id,user_id,cloud_state,object_key,generation,verified_size,sha256,stored_at,cloud_revision) VALUES(?,?,'STORED',?,?,6291456,?,CURRENT_TIMESTAMP,1)",bytes(id),bytes(owner),new com.ksh321.songrecord.api.storage.StorageObjectKeys.Final(owner,id,generation).value(),bytes(generation),"a".repeat(64));}
 static final class MutableClock extends Clock {Instant at=Instant.parse("2026-10-09T03:00:00Z");public ZoneId getZone(){return ZoneOffset.UTC;}public Clock withZone(ZoneId z){return this;}public Instant instant(){return at;}}
}
