package com.ksh321.songrecord.api.retention;
import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import com.ksh321.songrecord.api.auth.*;import com.ksh321.songrecord.api.idempotency.IdempotentMutations;import com.ksh321.songrecord.api.jobs.JobQueue;import com.ksh321.songrecord.api.storage.StorageObjectKeys;
import static com.ksh321.songrecord.api.retention.RetentionCandidateDatabaseChecks.*;import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
public final class CleanupDeletionDatabaseChecks {
 public static void verifyReal(com.ksh321.songrecord.api.storage.R2Storage storage)throws Exception {
  CleanupAuthorizationTests.withFixture(db->{CleanupDeletionTests.schema(db);var f=new Fixture(db);
   UUID id=CleanupAuthorizationDatabaseChecks.seed(db,f.owner,f.dev);UUID gen=uuid((byte[])db.queryForMap("SELECT generation FROM recording_asset WHERE recording_id=?",bytes(id)).get("generation"));var key=new StorageObjectKeys.Final(f.owner,id,gen);
   byte[] data="synthetic cleanup verification bytes".getBytes(java.nio.charset.StandardCharsets.UTF_8);String hash=java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(data));
   if(storage.existsFinal(key))throw new IllegalStateException("PROBE_COLLISION");
   boolean created=false;
   try{storage.ensureFinal(key,java.nio.ByteBuffer.wrap(data),hash);created=true;
    db.update("UPDATE recording_asset SET verified_size=?,sha256=? WHERE recording_id=?",data.length,hash,bytes(id));db.update("UPDATE storage_usage SET used_bytes=? WHERE user_id=?",data.length,bytes(f.owner));db.update("UPDATE global_storage_usage SET used_bytes=? WHERE id=1",data.length);
    var json=new tools.jackson.databind.json.JsonMapper();var response=f.confirmations.preview("fixture",f.dev.toString(),UUID.randomUUID().toString(),json.writeValueAsString(Map.of("recording_ids",List.of(id.toString())))).body();UUID token=UUID.fromString(json.readTree(response).get("items").get(0).get("token").asText());
    f.confirmations.confirm("fixture",f.dev.toString(),UUID.randomUUID().toString(),CleanupConfirmationDatabaseChecks.confirm(token.toString(),f.dev,"LOCAL_VERIFIED",hash,false));assertThat(f.authorizer.authorize(f.owner,token)).isEqualTo("DELETING");
    var worker=new CleanupWorker(f.queue,new CleanupDeletion(db,f.manager,f.queue,storage,f.clock));assertThat(worker.runOnce()).isTrue();assertThat(storage.existsFinal(key)).isFalse();assertThat(f.used()).isZero();assertThat(db.queryForObject("SELECT used_bytes FROM global_storage_usage WHERE id=1",Long.class)).isZero();assertThat(f.ledger()).isEqualTo(1);assertThat(f.cleanup(token)).isEqualTo("SUCCEEDED");assertThat(f.state(id)).isEqualTo("NONE");assertThat(worker.runOnce()).isFalse();assertThat(f.ledger()).isEqualTo(1);
   }finally{if(created && storage.existsFinal(key)){storage.deleteFinal(key);if(storage.existsFinal(key))throw new IllegalStateException("PROBE_CLEANUP_FAILED");}}
  });
 }
 public static void verify(JdbcTemplate db)throws Exception{
  var f=new Fixture(db);var port=new MemoryObjects(f);var deletion=new CleanupDeletion(db,f.manager,f.queue,port,f.clock);var worker=new CleanupWorker(f.queue,deletion);
  var a=f.seed();port.objects.add(a.key());port.loseResponse=true;long before=f.used();assertThat(worker.runOnce()).isTrue();assertThat(f.used()).isEqualTo(before-6291456);assertThat(f.state(a.id())).isEqualTo("NONE");assertThat(f.ledger()).isEqualTo(1);assertThat(f.cleanup(a.token())).isEqualTo("SUCCEEDED");assertThat(worker.runOnce()).isFalse();assertThat(f.ledger()).isEqualTo(1);assertThat(f.used()).isZero();assertThat(db.queryForObject("SELECT lifecycle_state FROM recording WHERE id=?",String.class,bytes(a.id()))).isEqualTo("ACTIVE");
  var b=f.seed();port.objects.add(b.key());port.failDelete=true;before=f.used();assertThat(worker.runOnce()).isTrue();assertThat(f.used()).isEqualTo(before);assertThat(f.ledger()).isEqualTo(1);assertThat(f.cleanup(b.token())).isEqualTo("RETRY_WAIT");port.failDelete=false;f.clock.at=f.clock.at.plusSeconds(6);assertThat(worker.runOnce()).isTrue();assertThat(f.used()).isZero();assertThat(f.ledger()).isEqualTo(2);
  var c=f.seed();port.objects.add(c.key());var lease=f.queue.claim(JobQueue.Type.ASSET_DELETE).orElseThrow();port.afterDelete=()->f.clock.at=f.clock.at.plusSeconds(1000);var effects=deletion.prepare(lease);assertThat(f.queue.complete(lease,effects)).isFalse();assertThat(f.used()).isEqualTo(6291456);assertThat(f.ledger()).isEqualTo(2);port.afterDelete=()->{};assertThat(worker.runOnce()).isTrue();assertThat(f.used()).isZero();assertThat(f.ledger()).isEqualTo(3);
  var d=f.seed();port.objects.add(d.key());var generation=UUID.randomUUID();var newKey=new StorageObjectKeys.Final(f.owner,d.id(),generation);port.objects.add(newKey);db.update("UPDATE recording_asset SET generation=?,object_key=?,cloud_revision=cloud_revision+1 WHERE recording_id=?",bytes(generation),newKey.value(),bytes(d.id()));int deletes=port.deletes;assertThat(worker.runOnce()).isTrue();assertThat(port.deletes).isEqualTo(deletes);assertThat(port.objects).contains(newKey,d.key());assertThat(f.used()).isEqualTo(6291456);assertThat(f.ledger()).isEqualTo(3);
  var e=f.seed();port.objects.add(e.key());db.update("INSERT INTO cloud_hold(id,user_id,recording_id,reason,related_operation_id,required_selection_revision) VALUES(?,?,?,'PENDING_REPLACEMENT',?,1)",bytes(UUID.randomUUID()),bytes(f.owner),bytes(e.id()),bytes(UUID.randomUUID()));before=f.used();deletes=port.deletes;assertThat(worker.runOnce()).isTrue();assertThat(port.deletes).isEqualTo(deletes);assertThat(f.state(e.id())).isEqualTo("STORED");assertThat(f.cleanup(e.token())).isEqualTo("CANCELLED");assertThat(f.used()).isEqualTo(before);assertThat(f.ledger()).isEqualTo(3);
  var queries=new RetentionQueries(db,f.access,f.manager);var result=queries.retention("fixture",f.dev.toString(),e.id().toString(),e.token().toString());assertThat(((Map<?,?>)result.get("cleanup_confirmation")).get("state")).isEqualTo("CANCELLED");assertThat(queries.retention("fixture",f.dev.toString(),d.id().toString(),e.token().toString()).get("cleanup_confirmation")).isNull();assertThat(queries.retention("fixture",f.dev.toString(),e.id().toString())).doesNotContainKey("cleanup_confirmation");
  var waiting=f.waiting();f.clock.at=f.clock.at.plusSeconds(900);assertThat(f.authorizer.authorize(f.owner,waiting.token())).isEqualTo("EXPIRED");assertThat(f.state(waiting.id())).isEqualTo("STORED");assertThat(db.queryForObject("SELECT COUNT(*) FROM job WHERE aggregate_id=?",Long.class,bytes(waiting.token()))).isZero();
 }
 static final class Fixture {
  final JdbcTemplate db;final UUID owner,dev;final AccountAccess access;final DataSourceTransactionManager manager;final CleanupConfirmationDatabaseChecks.MutableClock clock;final JobQueue queue;final CleanupConfirmations confirmations;final CleanupAuthorizations authorizer;
  Fixture(JdbcTemplate db){this.db=db;owner=account(db);dev=device(db,owner);db.update("INSERT INTO user_sync_state(user_id) VALUES(?)",bytes(owner));db.update("INSERT INTO user_entitlement(user_id,pinned_limit,quota_bytes) VALUES(?,10,1073741824)",bytes(owner));db.update("INSERT INTO storage_usage(user_id,used_bytes) VALUES(?,0)",bytes(owner));access=mock(AccountAccess.class);var account=mock(AccountAccess.Account.class);var principal=new SessionService.Principal(owner,dev,UUID.randomUUID());when(access.authenticate("fixture",dev.toString())).thenReturn(account);when(access.revalidate(account)).thenReturn(principal);when(account.principal()).thenReturn(principal);clock=new CleanupConfirmationDatabaseChecks.MutableClock();manager=new DataSourceTransactionManager(db.getDataSource());queue=new JobQueue(db,access,manager,clock,Duration.ofMinutes(2),5);confirmations=new CleanupConfirmations(db,access,new IdempotentMutations(db,access,manager,clock),clock);authorizer=new CleanupAuthorizations(db,manager,queue,clock);}
  Target seed(){var t=waiting();confirmations.confirm("fixture",dev.toString(),UUID.randomUUID().toString(),CleanupConfirmationDatabaseChecks.confirm(t.token().toString(),dev,"LOCAL_VERIFIED","a".repeat(64),false));assertThat(authorizer.authorize(owner,t.token())).isEqualTo("DELETING");return t;}
  Target waiting(){UUID id=CleanupAuthorizationDatabaseChecks.seed(db,owner,dev);db.update("UPDATE storage_usage SET used_bytes=used_bytes+6291456 WHERE user_id=?",bytes(owner));db.update("UPDATE global_storage_usage SET used_bytes=used_bytes+6291456 WHERE id=1");var json=new tools.jackson.databind.json.JsonMapper();String response=confirmations.preview("fixture",dev.toString(),UUID.randomUUID().toString(),json.writeValueAsString(Map.of("recording_ids",List.of(id.toString())))).body();UUID token=UUID.fromString(json.readTree(response).get("items").get(0).get("token").asText()),gen=uuid((byte[])db.queryForMap("SELECT generation FROM recording_asset WHERE recording_id=?",bytes(id)).get("generation"));return new Target(id,token,new StorageObjectKeys.Final(owner,id,gen));}
  long used(){return db.queryForObject("SELECT used_bytes FROM storage_usage WHERE user_id=?",Long.class,bytes(owner));}long ledger(){return db.queryForObject("SELECT COUNT(*) FROM deletion_ledger WHERE user_id=? AND entity_type='RECORDING_ASSET'",Long.class,bytes(owner));}String state(UUID id){return db.queryForObject("SELECT cloud_state FROM recording_asset WHERE user_id=? AND recording_id=?",String.class,bytes(owner),bytes(id));}String cleanup(UUID token){return db.queryForObject("SELECT state FROM cloud_cleanup WHERE user_id=? AND id=?",String.class,bytes(owner),bytes(token));}
 }
 record Target(UUID id,UUID token,StorageObjectKeys.Final key){}
 static final class MemoryObjects implements CleanupObjects {
  final Fixture f;final Set<StorageObjectKeys.Final> objects=new HashSet<>();boolean loseResponse,failDelete;int deletes;Runnable afterDelete=()->{};MemoryObjects(Fixture f){this.f=f;}
  public boolean existsFinal(StorageObjectKeys.Final key){assertThat(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive()).isFalse();return objects.contains(key);}
  public void deleteFinal(StorageObjectKeys.Final key)throws Exception{assertThat(org.springframework.transaction.support.TransactionSynchronizationManager.isActualTransactionActive()).isFalse();if(failDelete)throw new java.io.IOException("synthetic unavailable");deletes++;objects.remove(key);afterDelete.run();if(loseResponse){loseResponse=false;throw new java.io.IOException("synthetic lost reply");}}
 }
}
