package com.ksh321.songrecord.api.retention;
import java.util.*;import java.nio.*;import com.ksh321.songrecord.api.uploads.*;import com.ksh321.songrecord.api.auth.*;import com.ksh321.songrecord.api.idempotency.IdempotentMutations;import com.ksh321.songrecord.api.storage.StorageObjectKeys;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import static com.ksh321.songrecord.api.retention.RetentionCandidateDatabaseChecks.*;import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import static com.ksh321.songrecord.api.retention.UploadApprovalDatabaseChecks.assertCode;
public final class PinCompletionDatabaseChecks {
 public static void verify(JdbcTemplate db)throws Exception {
  var a=fixture(db);var finalizer=finalizer(db,a);var effects=finalizer.prepare(a.upload.lease(),audio());assertThat(current(db,a)).isEqualTo(a.old);assertThat(a.upload.jobs().complete(a.upload.lease(),effects)).isTrue();assertThat(current(db,a)).isEqualTo(a.upload.recording());assertThat(pending(db,a)).isNull();assertThat(used(db,a)).isEqualTo(6291459);assertThat(CleanupProtection.mandatory(db,a.upload.owner(),a.old)).isTrue();assertThat(state(db,a.old)).isEqualTo("STORED");assertThat(a.upload.jobs().complete(a.upload.lease(),effects)).isFalse();assertThat(used(db,a)).isEqualTo(6291459);
  // Already STORED replacement promotes immediately and leaves other automatic roles intact.
  UUID extra=recording(db,a.upload.owner(),a.dev,null,true,true,"VALIDATED");stored(db,a.upload.owner(),extra);db.update("UPDATE storage_usage SET used_bytes=used_bytes+6291456 WHERE user_id=?",bytes(a.upload.owner()));db.update("UPDATE global_storage_usage SET used_bytes=used_bytes+6291456 WHERE id=1");long version=version(db,a);var reply=a.pins.replace("fixture",a.dev.toString(),UUID.randomUUID().toString(),"1",PinReplacementDatabaseChecks.body(extra,version));assertThat(reply.body()).contains(extra.toString(),"\"pending_recording_id\":null");assertThat(current(db,a)).isEqualTo(extra);assertThat(CleanupProtection.mandatory(db,a.upload.owner(),a.old)).isTrue();
  // Worker recovery of an already stored pending replacement uses the same atomic transition.
  var recovered=fixture(db);db.update("INSERT INTO recording_asset(recording_id,user_id,cloud_state,cloud_revision,verified_size,sha256,generation,object_key,stored_at) VALUES(?,?,'STORED',1,3,?,?,?,CURRENT_TIMESTAMP)",bytes(recovered.upload.recording()),bytes(recovered.upload.owner()),"a".repeat(64),bytes(UUID.randomUUID()),"fixture/recovered/"+recovered.upload.recording());var transitions=new PinTransitions(db,recovered.manager);assertThat(transitions.finishStored(recovered.upload.owner(),1)).isTrue();assertThat(current(db,recovered)).isEqualTo(recovered.upload.recording());assertThat(pending(db,recovered)).isNull();assertThat(transitions.finishStored(recovered.upload.owner(),1)).isFalse();assertThat(state(db,recovered.old)).isEqualTo("STORED");assertThat(CleanupProtection.mandatory(db,recovered.upload.owner(),recovered.old)).isTrue();
  var b=fixture(db);var prepared=finalizer(db,b).prepare(b.upload.lease(),audio());String op=UUID.randomUUID().toString(),body="{\"base_revision\":1}";var cancelled=b.pins.cancelReplacement("fixture",b.dev.toString(),op,"1",body);assertThat(b.pins.cancelReplacement("fixture",b.dev.toString(),op,"1",body)).isEqualTo(cancelled);assertThat(current(db,b)).isEqualTo(b.old);assertThat(pending(db,b)).isNull();assertThatThrownBy(()->b.upload.jobs().complete(b.upload.lease(),prepared)).isInstanceOf(IllegalStateException.class);new UploadRecovery(db,b.manager,b.upload.clock()).cancel(b.upload.owner(),b.upload.attempt());assertThat(used(db,b)).isEqualTo(6291456);assertThat(state(db,b.old)).isEqualTo("STORED");
  var c=fixture(db);new UploadRecovery(db,c.manager,c.upload.clock()).failed(c.upload.lease(),"FILE_DECODE_FAILED");assertThat(current(db,c)).isEqualTo(c.old);assertThat(pending(db,c)).isNull();assertThat(used(db,c)).isEqualTo(6291456);assertThat(CleanupProtection.mandatory(db,c.upload.owner(),c.old)).isTrue();
  // Old attempt failure cannot clear a later request even for the identical recording UUID.
  var d=fixture(db);d.pins.cancelReplacement("fixture",d.dev.toString(),UUID.randomUUID().toString(),"1","{\"base_revision\":1}");UUID newOp=UUID.randomUUID();d.pins.replace("fixture",d.dev.toString(),newOp.toString(),"1",PinReplacementDatabaseChecks.body(d.upload.recording(),2));new UploadRecovery(db,d.manager,d.upload.clock()).failed(d.upload.lease(),"FILE_DECODE_FAILED");assertThat(current(db,d)).isEqualTo(d.old);assertThat(pending(db,d)).isEqualTo(d.upload.recording());assertThat(db.queryForObject("SELECT operation_id FROM pin_slot WHERE user_id=? AND slot_no=1",byte[].class,bytes(d.upload.owner()))).isEqualTo(bytes(newOp));
  var e=fixture(db);var promote=finalizer(db,e).prepare(e.upload.lease(),audio());var race=UploadReservationDatabaseChecks.race(()->{try{return e.upload.jobs().complete(e.upload.lease(),promote);}catch(IllegalStateException changed){return "NOT_CLOUD_TARGET";}},()->e.pins.cancelReplacement("fixture",e.dev.toString(),UUID.randomUUID().toString(),"1","{\"base_revision\":1}"));assertThat(current(db,e)).isIn(e.old,e.upload.recording());assertThat(pending(db,e)).isNull();assertThat(state(db,e.old)).isEqualTo("STORED");if(current(db,e).equals(e.old)){new UploadRecovery(db,e.manager,e.upload.clock()).cancel(e.upload.owner(),e.upload.attempt());assertThat(used(db,e)).isEqualTo(6291456);}else{assertThat(race).contains("REVISION_CONFLICT");assertThat(used(db,e)).isEqualTo(6291459);}assertThat(CleanupProtection.mandatory(db,e.upload.owner(),e.old)).isTrue();
  var f=fixture(db);db.update("UPDATE recording_asset SET cloud_revision=? WHERE recording_id=?",Long.MAX_VALUE,bytes(f.old));assertCode(()->f.pins.cancelReplacement("fixture",f.dev.toString(),UUID.randomUUID().toString(),"1","{\"base_revision\":1}"),"REVISION_LIMIT_REACHED");assertThat(current(db,f)).isEqualTo(f.old);assertThat(pending(db,f)).isEqualTo(f.upload.recording());assertThat(version(db,f)).isEqualTo(1);assertThat(used(db,f)).isEqualTo(6291456);
 }
 record Fixture(UploadFinalizationDatabaseChecks.Fixture upload,UUID old,UUID dev,PinSlots pins,DataSourceTransactionManager manager){}
 static Fixture fixture(JdbcTemplate db){var u=UploadFinalizationDatabaseChecks.fixture(db);UUID owner=u.owner(),dev=uuid((byte[])db.queryForMap("SELECT origin_device_id FROM recording WHERE id=?",bytes(u.recording())).get("origin_device_id")),song=song(db,owner),old=recording(db,owner,dev,song,true,true,"VALIDATED");stored(db,owner,old);db.update("UPDATE song SET representative_recording_id=? WHERE id=?",bytes(old),bytes(song));db.update("UPDATE pin_slot SET current_recording_id=? WHERE user_id=? AND slot_no=1",bytes(old),bytes(owner));db.update("UPDATE storage_usage SET used_bytes=6291456 WHERE user_id=?",bytes(owner));db.update("UPDATE global_storage_usage SET used_bytes=used_bytes+6291456 WHERE id=1");var access=mock(AccountAccess.class);var account=mock(AccountAccess.Account.class);var principal=new SessionService.Principal(owner,dev,UUID.randomUUID());when(access.authenticate("fixture",dev.toString())).thenReturn(account);when(access.revalidate(account)).thenReturn(principal);when(account.principal()).thenReturn(principal);var manager=new DataSourceTransactionManager(db.getDataSource());return new Fixture(u,old,dev,new PinSlots(db,access,new IdempotentMutations(db,access,manager,u.clock())),manager);}
 static void stored(JdbcTemplate db,UUID owner,UUID id){UUID gen=UUID.randomUUID();db.update("INSERT INTO recording_asset(recording_id,user_id,cloud_state,cloud_revision,verified_size,sha256,generation,object_key,stored_at) VALUES(?,?,'STORED',1,6291456,?,?,?,CURRENT_TIMESTAMP)",bytes(id),bytes(owner),"a".repeat(64),bytes(gen),new StorageObjectKeys.Final(owner,id,gen).value());}
 static AudioValidator.Validated audio(){var a=mock(AudioValidator.Validated.class);when(a.bytes()).thenAnswer(x->ByteBuffer.wrap(new byte[]{1,2,3}).asReadOnlyBuffer());when(a.sha256()).thenReturn("a".repeat(64));return a;}
 static UploadFinalization finalizer(JdbcTemplate db,Fixture f){return new UploadFinalization(db,(key,data,hash)->{},f.upload.clock());}
 static UUID current(JdbcTemplate db,Fixture f){return uuid(db.queryForObject("SELECT current_recording_id FROM pin_slot WHERE user_id=? AND slot_no=1",byte[].class,bytes(f.upload.owner())));}static UUID pending(JdbcTemplate db,Fixture f){byte[] value=db.queryForObject("SELECT pending_recording_id FROM pin_slot WHERE user_id=? AND slot_no=1",byte[].class,bytes(f.upload.owner()));return value==null?null:uuid(value);}static long version(JdbcTemplate db,Fixture f){return db.queryForObject("SELECT revision FROM pin_slot WHERE user_id=? AND slot_no=1",Long.class,bytes(f.upload.owner()));}static long used(JdbcTemplate db,Fixture f){return db.queryForObject("SELECT used_bytes FROM storage_usage WHERE user_id=?",Long.class,bytes(f.upload.owner()));}static String state(JdbcTemplate db,UUID id){return db.queryForObject("SELECT cloud_state FROM recording_asset WHERE recording_id=?",String.class,bytes(id));}
}
