package com.ksh321.songrecord.api.retention;
import java.util.*;import java.time.*;import com.ksh321.songrecord.api.auth.*;import com.ksh321.songrecord.api.idempotency.IdempotentMutations;import com.ksh321.songrecord.api.uploads.UploadApproval;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import static com.ksh321.songrecord.api.retention.RetentionCandidateDatabaseChecks.*;import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;import static org.mockito.Mockito.*;import static org.assertj.core.api.Assertions.*;import static com.ksh321.songrecord.api.retention.UploadApprovalDatabaseChecks.assertCode;
public final class PinReplacementDatabaseChecks {
 public static String body(UUID id,long revision){return "{\"recording_id\":\""+id+"\",\"base_revision\":"+revision+"}";}
 public static void verify(JdbcTemplate db)throws Exception{
  UUID owner=account(db),dev=device(db,owner);db.update("INSERT INTO user_sync_state(user_id) VALUES(?)",bytes(owner));db.update("INSERT INTO user_entitlement(user_id,pinned_limit,quota_bytes) VALUES(?,10,?)",bytes(owner),62914560+5242880);db.update("INSERT INTO storage_usage(user_id,used_bytes) VALUES(?,62914560)",bytes(owner));db.update("UPDATE global_storage_usage SET used_bytes=62914560,reserved_bytes=0 WHERE id=1");
  var access=mock(AccountAccess.class);var a=mock(AccountAccess.Account.class);var principal=new SessionService.Principal(owner,dev,UUID.randomUUID());when(access.authenticate("fixture",dev.toString())).thenReturn(a);when(access.revalidate(a)).thenReturn(principal);when(a.principal()).thenReturn(principal);var manager=new DataSourceTransactionManager(db.getDataSource());var mutations=new IdempotentMutations(db,access,manager,Clock.systemUTC());var pins=new PinSlots(db,access,mutations);var approvals=new UploadApproval(db,access,manager,Clock.systemUTC(),mutations);var old=new ArrayList<UUID>();
  for(int i=0;i<10;i++){UUID id=recording(db,owner,dev,null,true,true,"VALIDATED"),generation=UUID.randomUUID();old.add(id);db.update("INSERT INTO recording_asset(recording_id,user_id,cloud_state,cloud_revision,verified_size,sha256,generation,object_key,stored_at) VALUES(?,?,'STORED',1,6291456,?,?,?,CURRENT_TIMESTAMP)",bytes(id),bytes(owner),"a".repeat(64),bytes(generation),new com.ksh321.songrecord.api.storage.StorageObjectKeys.Final(owner,id,generation).value());pins.reserve("fixture",dev.toString(),UUID.randomUUID().toString(),PinReservationDatabaseChecks.body(id,1));}
  UUID target=recording(db,owner,dev,null,true,true,"VALIDATED"),next=recording(db,owner,dev,null,true,true,"VALIDATED");String op=UUID.randomUUID().toString();var result=pins.replace("fixture",dev.toString(),op,"1",body(target,1));assertThat(pins.replace("fixture",dev.toString(),op,"1",body(target,1))).isEqualTo(result);assertThat(result.body()).contains(old.get(0).toString(),target.toString());
  assertThat(db.queryForObject("SELECT COUNT(*) FROM pin_slot WHERE user_id=? AND (current_recording_id IS NOT NULL OR pending_recording_id IS NOT NULL)",Long.class,bytes(owner))).isEqualTo(10);assertThat(CleanupProtection.mandatory(db,owner,old.get(0))).isTrue();assertThat(CleanupProtection.mandatory(db,owner,target)).isTrue();
  assertCode(()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"1",body(next,1)),"REVISION_CONFLICT");assertCode(()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"1",body(next,2)),"PIN_REPLACEMENT_IN_PROGRESS");assertCode(()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"2",body(target,1)),"PIN_ALREADY_IN_SLOT");
  assertCode(()->approvals.approve(a,target,6291456,"a".repeat(64)),"QUOTA_EXCEEDED");assertThat(db.queryForObject("SELECT reserved_bytes FROM storage_usage WHERE user_id=?",Long.class,bytes(owner))).isZero();assertThat(db.queryForObject("SELECT COUNT(*) FROM recording_upload WHERE user_id=?",Long.class,bytes(owner))).isZero();assertThat(db.queryForObject("SELECT current_recording_id FROM pin_slot WHERE user_id=? AND slot_no=1",byte[].class,bytes(owner))).isEqualTo(bytes(old.get(0)));
  db.update("UPDATE user_entitlement SET quota_bytes=62914560+6291456 WHERE user_id=?",bytes(owner));db.update("UPDATE global_storage_usage SET primary_quota_bytes=62914560+5242880 WHERE id=1");assertCode(()->approvals.approve(a,target,6291456,"a".repeat(64)),"QUOTA_EXCEEDED");db.update("UPDATE global_storage_usage SET primary_quota_bytes=62914560+6291456 WHERE id=1");assertThat(approvals.approve(a,target,6291456,"a".repeat(64))).isNotNull();assertThat(db.queryForObject("SELECT reserved_bytes FROM storage_usage WHERE user_id=?",Long.class,bytes(owner))).isEqualTo(6291456);assertThat(db.queryForObject("SELECT cloud_state FROM recording_asset WHERE recording_id=?",String.class,bytes(old.get(0)))).isEqualTo("STORED");
  UUID second=recording(db,owner,dev,null,true,true,"VALIDATED"),third=recording(db,owner,dev,null,true,true,"VALIDATED");var race=UploadReservationDatabaseChecks.race(()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"2",body(second,1)),()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"2",body(third,1)));assertThat(race).contains("REVISION_CONFLICT");assertThat(race.stream().filter(IdempotentMutations.Reply.class::isInstance).count()).isEqualTo(1);
  UUID foreign=UUID.randomUUID();assertCode(()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"3",body(foreign,1)),"RESOURCE_NOT_FOUND");db.update("UPDATE recording SET metadata_state='DRAFT' WHERE id=?",bytes(next));assertCode(()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"3",body(next,1)),"PIN_NOT_ELIGIBLE");db.update("UPDATE recording SET metadata_state='SAVED' WHERE id=?",bytes(next));db.update("INSERT INTO recording_asset(recording_id,user_id,cloud_state,cloud_revision,verified_size,sha256,generation,object_key,stored_at) VALUES(?,?,'DELETING',1,6291456,?,?,'fixture/deleting',CURRENT_TIMESTAMP)",bytes(next),bytes(owner),"a".repeat(64),bytes(UUID.randomUUID()));assertCode(()->pins.replace("fixture",dev.toString(),UUID.randomUUID().toString(),"3",body(next,1)),"FILE_CLEANUP_IN_PROGRESS");
 }
}
