package com.ksh321.songrecord.api.retention;
import com.ksh321.songrecord.api.uploads.*;import com.ksh321.songrecord.api.storage.StorageObjectKeys;
import java.nio.*;import java.time.*;import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import static com.ksh321.songrecord.api.songs.SongQueryKeys.bytes;import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;
public final class UploadInventoryDatabaseChecks {
 public static void verify(JdbcTemplate db)throws Exception{
  byte[] content={1,2,3};String hash=HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(content));var f=UploadFinalizationDatabaseChecks.fixture(db,hash);var manager=new DataSourceTransactionManager(db.getDataSource());var objects=new Fake();var inventory=new UploadInventory(db,manager,objects,f.clock());
  var active=new StorageObjectKeys.Temporary(f.owner(),f.recording(),f.attempt());var orphan=new StorageObjectKeys.Temporary(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID());
  objects.temp.add(new UploadObjectInventory.Entry(active.value(),3,f.clock().instant()));objects.temp.add(new UploadObjectInventory.Entry(orphan.value(),4,f.clock().instant().minusSeconds(172800)));objects.temp.add(new UploadObjectInventory.Entry("unmanaged/keep",UploadInventory.TEMP_LIMIT,f.clock().instant()));
  var first=inventory.temporary();assertThat(first.protectedObjects()).isEqualTo(1);assertThat(first.removed()).isEqualTo(1);assertThat(objects.deleted).containsExactly(orphan.value());assertThat(db.queryForObject("SELECT temp_observed_bytes FROM global_storage_usage WHERE id=1",Long.class)).isGreaterThanOrEqualTo(UploadInventory.TEMP_LIMIT);
  var access=mock(com.ksh321.songrecord.api.auth.AccountAccess.class);var account=mock(com.ksh321.songrecord.api.auth.AccountAccess.Account.class);when(access.revalidate(account)).thenReturn(new com.ksh321.songrecord.api.auth.SessionService.Principal(f.owner(),UUID.randomUUID(),UUID.randomUUID()));
  var device=com.ksh321.songrecord.api.songs.SongQueryKeys.uuid(db.queryForObject("SELECT origin_device_id FROM recording WHERE id=?",byte[].class,bytes(f.recording())));var newRecording=RetentionCandidateDatabaseChecks.recording(db,f.owner(),device,null,false,false,"VALIDATED");
  UploadApprovalDatabaseChecks.assertCode(()->new UploadReservations(db,access,manager,f.clock()).reserve(account,new UploadReservations.Request(newRecording,3,hash,1)),"UPLOAD_BUDGET_LOCKED");
  new UploadRecovery(db,manager,f.clock()).cancel(f.owner(),f.attempt());f.clock().now=f.clock().now.plusSeconds(601);objects.temp.clear();objects.temp.add(new UploadObjectInventory.Entry(active.value(),3,f.clock().instant()));inventory.temporary();assertThat(objects.deleted).contains(active.value());
  objects.temp.clear();db.update("UPDATE global_storage_usage SET upload_locked=TRUE WHERE id=1");inventory.temporary();assertThat(db.queryForObject("SELECT upload_locked FROM global_storage_usage WHERE id=1",Boolean.class)).isTrue();
  db.update("UPDATE global_storage_usage SET upload_locked=FALSE WHERE id=1");var stored=UploadFinalizationDatabaseChecks.fixture(db,hash);db.update("UPDATE global_storage_usage SET upload_locked=TRUE WHERE id=1");var audio=mock(AudioValidator.Validated.class);when(audio.bytes()).thenAnswer(c->ByteBuffer.wrap(content).asReadOnlyBuffer());when(audio.sha256()).thenReturn(hash);
  var finalizer=new UploadFinalization(db,(key,buffer,h)->{var data=new byte[buffer.remaining()];buffer.get(data);objects.data.put(key.value(),data);objects.finals.add(new UploadObjectInventory.Entry(key.value(),data.length,stored.clock().instant()));},stored.clock());
  assertThat(stored.jobs().complete(stored.lease(),finalizer.prepare(stored.lease(),audio))).isTrue();var day=new UploadInventory(db,manager,objects,stored.clock());assertThat(day.daily().issues()).isZero();
  var orphanFinal=new StorageObjectKeys.Final(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID());objects.finals.add(new UploadObjectInventory.Entry(orphanFinal.value(),4,stored.clock().instant().minusSeconds(3600)));assertThat(day.daily().removed()).isEqualTo(1);assertThat(objects.deleted).contains(orphanFinal.value());
  String finalKey=db.queryForObject("SELECT final_key FROM recording_upload WHERE id=?",String.class,bytes(stored.attempt()));objects.data.put(finalKey,new byte[]{4,5,6});assertThat(day.daily().issues()).isGreaterThan(0);assertThat(db.queryForObject("SELECT reconciliation_locked FROM global_storage_usage WHERE id=1",Boolean.class)).isTrue();assertThat(db.queryForObject("SELECT used_bytes FROM storage_usage WHERE user_id=?",Long.class,bytes(stored.owner()))).isEqualTo(3);
  objects.data.put(finalKey,content);assertThat(day.daily().issues()).isZero();assertThat(db.queryForObject("SELECT reconciliation_locked FROM global_storage_usage WHERE id=1",Boolean.class)).isFalse();assertThat(db.queryForObject("SELECT upload_locked FROM global_storage_usage WHERE id=1",Boolean.class)).isTrue();
  objects.data.clear();assertThat(day.daily().issues()).isGreaterThan(0);assertThat(db.queryForObject("SELECT cloud_state FROM recording_asset WHERE recording_id=?",String.class,bytes(stored.recording()))).isEqualTo("STORED");
  objects.failTemp=true;assertThatThrownBy(inventory::temporary).isInstanceOf(java.io.IOException.class);assertThat(db.queryForObject("SELECT temp_observed_bytes FROM global_storage_usage WHERE id=1",Long.class)).isGreaterThanOrEqualTo(UploadInventory.TEMP_LIMIT);objects.failTemp=false;objects.temp.clear();inventory.temporary();assertThat(db.queryForObject("SELECT temp_observed_bytes FROM global_storage_usage WHERE id=1",Long.class)).isZero();
 }
 static final class Fake implements UploadObjectInventory {
  final List<Entry> temp=new ArrayList<>(),finals=new ArrayList<>();final Map<String,byte[]> data=new HashMap<>();final List<String> deleted=new ArrayList<>();
  boolean failTemp;public void temporaryObjects(Visitor v)throws Exception{if(failTemp)throw new java.io.IOException("INVENTORY_INCOMPLETE");for(var e:List.copyOf(temp))v.accept(e);}public void finalObjects(Visitor v)throws Exception{for(var e:List.copyOf(finals))v.accept(e);}public Optional<ByteBuffer> readFinal(StorageObjectKeys.Final key){return Optional.ofNullable(data.get(key.value())).map(ByteBuffer::wrap);}public void deleteTemporary(StorageObjectKeys.Temporary key){deleted.add(key.value());}public void deleteUncommittedFinal(StorageObjectKeys.Final key){deleted.add(key.value());data.remove(key.value());}
 }
}
