package com.ksh321.songrecord.api.charts;
import com.ksh321.songrecord.api.auth.*;import com.ksh321.songrecord.api.config.SecurityConfig;import com.ksh321.songrecord.api.karaoke.SourceTokens;import com.ksh321.songrecord.api.web.*;
import java.time.*;import java.nio.charset.StandardCharsets;import java.util.*;
import org.junit.jupiter.api.*;import org.springframework.context.annotation.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;import org.springframework.mock.web.MockServletContext;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.setup.MockMvcBuilders;import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;import org.springframework.web.servlet.config.annotation.EnableWebMvc;import tools.jackson.databind.json.JsonMapper;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.security.test.web.servlet.setup.SecurityMockMvcConfigurers.springSecurity;
class ChartHttpTests {
    AnnotationConfigWebApplicationContext context;MockMvc mvc;UUID device=UUID.randomUUID();
    @Configuration @EnableWebMvc @EnableWebSecurity @Import({ChartQueryConfiguration.class,ChartController.class,SecurityConfig.class,GlobalExceptionHandler.class}) static class Config {
        @Bean(destroyMethod="close") ChartDatabaseFixture fixture()throws Exception{return new ChartDatabaseFixture();}
        @Bean JdbcTemplate jdbc(ChartDatabaseFixture f){return f.jdbc;}@Bean PlatformTransactionManager manager(ChartDatabaseFixture f){return f.manager;}
        @Bean SessionService sessions(){return mock(SessionService.class);}@Bean AccountAccess access(SessionService s){return new AccountAccess(s);}@Bean SourceTokens tokens(){return new SourceTokens(new byte[32],Clock.systemUTC());}
    }
    @BeforeEach void setup(){context=new AnnotationConfigWebApplicationContext();context.setServletContext(new MockServletContext());context.getEnvironment().setActiveProfiles("dev");context.register(Config.class);context.refresh();mvc=MockMvcBuilders.webAppContextSetup(context).apply(springSecurity()).build();when(context.getBean(SessionService.class).authenticate("fixture",device)).thenReturn(new SessionService.Principal(UUID.randomUUID(),device,UUID.randomUUID()));for(String brand:List.of("TJ","KY")){var scope=ChartScope.parse(brand,"MONTHLY");var f=context.getBean(ChartDatabaseFixture.class);var p=new ChartPublication(f.jdbc,f.manager,f.validation,Clock.systemUTC());var ticket=p.begin(scope);var id=f.staging.stage(scope,("[{\"brand\":\""+scope.providerBrand()+"\",\"no\":\"00123\",\"title\":\"원본 (LIVE)\",\"singer\":\"가수\"}]").getBytes(StandardCharsets.UTF_8),Instant.parse("2026-10-01T00:00:00Z"));p.publish(scope,ticket,id);}}
    @AfterEach void close(){context.close();}
    MockHttpServletRequestBuilder request(String brand,String period){return get("/v1/charts/popular").header("Authorization","Bearer fixture").header("X-Device-Id",device.toString()).param("brand",brand).param("period",period);}
    @Test void authenticationValidationSourceProofAndKyPolicyAreEnforced()throws Exception{
        assertThat(mvc.perform(get("/v1/charts/popular").param("brand","TJ").param("period","MONTHLY")).andReturn().getResponse().getStatus()).isEqualTo(401);
        var response=mvc.perform(request("TJ","MONTHLY")).andReturn().getResponse();assertThat(response.getStatus()).isEqualTo(200);assertThat(response.getHeader("Cache-Control")).isEqualTo("no-store");var root=new JsonMapper().readTree(response.getContentAsString());assertThat(root.get("stale").asBoolean()).isFalse();var item=root.get("items").get(0);assertThat(item.get("number").asString()).isEqualTo("00123");assertThat(item.get("title").asString()).isEqualTo("원본 (LIVE)");var proof=context.getBean(SourceTokens.class).read(item.get("source_token").asString());assertThat(proof.candidate().number()).isEqualTo("00123");assertThat(proof.expiresAt()).isEqualTo(proof.issuedAt().plus(Duration.ofHours(24)));
        var ky=new JsonMapper().readTree(mvc.perform(request("KY","MONTHLY")).andReturn().getResponse().getContentAsString());assertThat(ky.get("items").get(0).get("source_token").isNull()).isTrue();assertThat(ky.has("matched_song_id")).isFalse();
        for(var invalid:List.of(request("TJ","MONTHLY").param("brand","KY"),request("TJ","MONTHLY").param("year_month","2026-01"),request("tj","MONTHLY"),request("TJ","YEARLY"))){var bad=mvc.perform(invalid).andReturn().getResponse();assertThat(bad.getStatus()).isEqualTo(400);assertThat(bad.getContentAsString()).contains("VALIDATION_FAILED");}
        assertThat(mvc.perform(post("/v1/charts/popular")).andReturn().getResponse().getStatus()).isEqualTo(403);assertThat(mvc.perform(request("TJ","DAILY")).andReturn().getResponse().getStatus()).isEqualTo(503);
    }
    @Test void revokedSessionDuringReadCannotReturnSourceTokens()throws Exception{var session=context.getBean(SessionService.class);when(session.authenticate("fixture",device)).thenReturn(new SessionService.Principal(UUID.randomUUID(),device,UUID.randomUUID()));assertThat(mvc.perform(request("TJ","MONTHLY")).andReturn().getResponse().getStatus()).isEqualTo(200);var principal=new SessionService.Principal(UUID.randomUUID(),device,UUID.randomUUID());when(session.authenticate("fixture",device)).thenReturn(principal,principal).thenThrow(new ApiException(org.springframework.http.HttpStatus.UNAUTHORIZED,"AUTH_INVALID_SESSION","다시 로그인",false,Map.of()));assertThat(mvc.perform(request("TJ","MONTHLY")).andReturn().getResponse().getStatus()).isEqualTo(401);}
}
