package com.ksh321.songrecord.api.charts;
import java.time.*;import java.nio.charset.StandardCharsets;import java.util.*;
import com.ksh321.songrecord.api.songs.CandidateVerifier.Brand;
import com.ksh321.songrecord.api.web.ApiException;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.*;
class ChartQueryTests {
    UUID publish(ChartDatabaseFixture f,ChartScope scope){var p=new ChartPublication(f.jdbc,f.manager,f.validation,Clock.systemUTC());var ticket=p.begin(scope);var raw="[{\"brand\":\""+scope.providerBrand()+"\",\"no\":\"00999\",\"title\":\"원본 (LIVE)\",\"singer\":\"가수\"},{\"brand\":\""+scope.providerBrand()+"\",\"no\":\"00123\",\"title\":\"둘째\",\"singer\":\"가수\"}]";var id=f.staging.stage(scope,raw.getBytes(StandardCharsets.UTF_8),Instant.parse("2026-10-01T00:00:00Z"));assertThat(p.publish(scope,ticket,id)).isTrue();return id;}
    @Test void allSixScopesReadOnlyTheirImmutableGenerationAndPreserveArrayOrder()throws Exception{try(var f=new ChartDatabaseFixture()){var query=new ChartQuery(f.jdbc,f.manager);for(var b:Brand.values())for(var p:ChartScope.Period.values()){var scope=new ChartScope(b,p);publish(f,scope);var result=query.read(scope);assertThat(result.scope()).isEqualTo(scope);assertThat(result.stale()).isFalse();assertThat(result.fetchedAt()).isEqualTo(Instant.parse("2026-10-01T00:00:00Z"));assertThat(result.items()).extracting(ChartValidation.Item::number).containsExactly("00999","00123");assertThat(result.items()).extracting(ChartValidation.Item::position).containsExactly(1,2);}assertThat(f.jdbc.queryForObject("SELECT COUNT(*) FROM chart_snapshot",Integer.class)).isEqualTo(6);}}
    @Test void failedOrInFlightAttemptReturnsSameOldContentAsStaleAndNoCrossPeriodFallback()throws Exception{try(var f=new ChartDatabaseFixture()){var scope=ChartScope.parse("TJ","MONTHLY");publish(f,scope);var query=new ChartQuery(f.jdbc,f.manager);var before=query.read(scope);new ChartPublication(f.jdbc,f.manager,f.validation,Clock.systemUTC()).begin(scope);var after=query.read(scope);assertThat(after.stale()).isTrue();assertThat(after.revision()).isEqualTo(before.revision());assertThat(after.fetchedAt()).isEqualTo(before.fetchedAt());assertThat(after.items()).isEqualTo(before.items());assertThatThrownBy(()->query.read(ChartScope.parse("TJ","DAILY"))).isInstanceOfSatisfying(ApiException.class,e->{assertThat(e.code()).isEqualTo("CHART_SOURCE_UNAVAILABLE");assertThat(e.retryable()).isTrue();});}}
    @Test void unpublishedAndCorruptedItemsNeverAppearAsAValidEmptyOrPartialChart()throws Exception{try(var f=new ChartDatabaseFixture()){var scope=ChartScope.parse("KY","WEEKLY");var query=new ChartQuery(f.jdbc,f.manager);assertThatThrownBy(()->query.read(scope)).isInstanceOf(ApiException.class);var id=publish(f,scope);f.jdbc.update("DELETE FROM chart_item WHERE snapshot_id=? AND position=2",ChartStaging.bytes(id));assertThatThrownBy(()->query.read(scope)).isInstanceOf(ApiException.class);}}
}
