package com.ksh321.songrecord.api.retention;
import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.*;import org.springframework.transaction.support.TransactionTemplate;
import com.ksh321.songrecord.api.jobs.JobQueue;import com.ksh321.songrecord.api.locking.LockOrder;
import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;
/** A short locked decision. Object I/O belongs to the separately leased ASSET_DELETE worker. */
public final class CleanupAuthorizations {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final JobQueue queue;private final Clock clock;private UUID cursor;
 public CleanupAuthorizations(JdbcTemplate db,PlatformTransactionManager manager,JobQueue queue,Clock clock){this.db=db;this.queue=queue;this.clock=clock;tx=new TransactionTemplate(manager);tx.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);tx.setTimeout(30);}
 public String authorize(UUID owner,UUID token){LockOrder.requireOutsideTransaction();return tx.execute(s->{
  LockOrder.before(LockOrder.Rank.USER_SYNC,owner.toString());if(db.queryForList("SELECT user_id FROM user_sync_state WHERE user_id=? FOR UPDATE",bytes(owner)).isEmpty())return "MISSING";
  var identities=db.queryForList("SELECT recording_id FROM cloud_cleanup WHERE user_id=? AND id=?",bytes(owner),bytes(token));if(identities.isEmpty())return "MISSING";UUID recording=uuid((byte[])identities.getFirst().get("recording_id"));
  LockOrder.before(LockOrder.Rank.RECORDING_ASSET,owner+"/"+recording);var assets=db.queryForList("SELECT cloud_state,generation,sha256,cloud_revision FROM recording_asset WHERE user_id=? AND recording_id=? FOR UPDATE",bytes(owner),bytes(recording));
  var rows=db.query("SELECT state,generation,expected_sha256,expected_cloud_revision,confirmation_mode,confirmation_expires_at,created_at FROM cloud_cleanup WHERE user_id=? AND id=? FOR UPDATE",(rs,n)->new Captured(rs.getString(1),rs.getBytes(2),rs.getString(3),rs.getLong(4),rs.getString(5),rs.getObject(6,LocalDateTime.class),rs.getObject(7,LocalDateTime.class)),bytes(owner),bytes(token));if(rows.isEmpty())return "MISSING";var c=rows.getFirst();var now=CleanupConfirmations.stamp(clock.instant());if(c.state().equals("WAITING_CONFIRMATION") && !c.created().plusSeconds(900).isAfter(now))return terminal(owner,token,c,"EXPIRED","TOKEN_EXPIRED",now);if(!c.state().equals("CONFIRMED"))return c.state();
  if(c.expiry()==null || c.mode()==null || !Set.of("LOCAL_VERIFIED","USER_CONFIRMED_LOSS").contains(c.mode()) || !c.expiry().isAfter(now))return terminal(owner,token,c,"EXPIRED","TOKEN_EXPIRED",now);
  if(db.queryForList("SELECT id FROM app_user WHERE id=? AND status='ACTIVE'",bytes(owner)).isEmpty() || db.queryForList("SELECT id FROM recording WHERE user_id=? AND id=? AND lifecycle_state='ACTIVE' AND metadata_state='SAVED'",bytes(owner),bytes(recording)).isEmpty())return terminal(owner,token,c,"CANCELLED","OWNER_OR_RECORDING_INACTIVE",now);
  if(assets.size()!=1)return terminal(owner,token,c,"CANCELLED","OBJECT_CHANGED",now);var a=assets.getFirst();if(!"STORED".equals(a.get("cloud_state")) || !Arrays.equals(c.generation(),(byte[])a.get("generation")) || !c.hash().equals(a.get("sha256")) || c.revision()!=((Number)a.get("cloud_revision")).longValue())return terminal(owner,token,c,"CANCELLED","OBJECT_CHANGED",now);
  if(CleanupProtection.mandatory(db,owner,recording) || !db.queryForList("SELECT id FROM cloud_hold WHERE user_id=? AND recording_id=? AND reason NOT IN ('WAITING_LOCAL_CONFIRM','ORPHAN_KEEP') FOR UPDATE",bytes(owner),bytes(recording)).isEmpty())return terminal(owner,token,c,"CANCELLED","FILE_STILL_PROTECTED",now);
  long next=PinSlots.increment(c.revision());db.update("DELETE FROM cloud_hold WHERE user_id=? AND recording_id=? AND reason IN ('WAITING_LOCAL_CONFIRM','ORPHAN_KEEP')",bytes(owner),bytes(recording));
  if(db.update("UPDATE recording_asset SET cloud_state='DELETING',cloud_revision=?,updated_at=? WHERE user_id=? AND recording_id=? AND cloud_state='STORED' AND cloud_revision=?",next,now,bytes(owner),bytes(recording),c.revision())!=1)throw new IllegalStateException("Cleanup asset fence changed");
  db.update("UPDATE cloud_cleanup SET state='DELETING',error_code=NULL,updated_at=? WHERE user_id=? AND id=?",now,bytes(owner),bytes(token));RetentionAssetEvents.publish(db,owner,recording,next,clock);
  var payload=new LinkedHashMap<String,Object>();payload.put("kind","SERVER_COPY_CLEANUP");payload.put("cleanup_id",token.toString());payload.put("recording_id",recording.toString());payload.put("generation",uuid(c.generation()).toString());payload.put("sha256",c.hash());payload.put("deleting_revision",next);
  queue.enqueueOwnedMaintenance(owner,JobQueue.Type.ASSET_DELETE,token,token,new tools.jackson.databind.json.JsonMapper().writeValueAsString(payload));return "DELETING";
 });}
 private String terminal(UUID owner,UUID token,Captured c,String state,String code,LocalDateTime now){var finished=now.isBefore(c.created())?c.created():now;db.update("UPDATE cloud_cleanup SET state=?,error_code=?,completed_at=?,updated_at=? WHERE user_id=? AND id=?",state,code,finished,finished,bytes(owner),bytes(token));return state;}
 private record Captured(String state,byte[] generation,String hash,long revision,String mode,LocalDateTime expiry,LocalDateTime created){}
 /** Bounded cursor avoids expired/protected first-page starvation. No network inside transactions. */
 public synchronized void refresh(){LockOrder.requireOutsideTransaction();var rows=cursor==null?db.queryForList("SELECT id,user_id FROM cloud_cleanup WHERE state IN ('WAITING_CONFIRMATION','CONFIRMED') ORDER BY id LIMIT 100"):db.queryForList("SELECT id,user_id FROM cloud_cleanup WHERE state IN ('WAITING_CONFIRMATION','CONFIRMED') AND id>? ORDER BY id LIMIT 100",bytes(cursor));if(rows.isEmpty()){cursor=null;return;}for(var row:rows){UUID id=uuid((byte[])row.get("id"));authorize(uuid((byte[])row.get("user_id")),id);cursor=id;}}
}
