package com.ksh321.songrecord.api.retention;
import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.*;import org.springframework.transaction.support.TransactionTemplate;
import com.ksh321.songrecord.api.jobs.JobQueue;import com.ksh321.songrecord.api.locking.LockOrder;import com.ksh321.songrecord.api.storage.StorageObjectKeys;
import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;
/** Network runs between short locked snapshots and lease-fenced atomic DB completion. */
public final class CleanupDeletion {
 private final JdbcTemplate db;private final TransactionTemplate tx;private final JobQueue queue;private final CleanupObjects objects;private final Clock clock;
 public CleanupDeletion(JdbcTemplate db,PlatformTransactionManager manager,JobQueue queue,CleanupObjects objects,Clock clock){this.db=db;this.queue=queue;this.objects=objects;this.clock=clock;tx=new TransactionTemplate(manager);tx.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);tx.setTimeout(30);}
 public Runnable prepare(JobQueue.Lease lease)throws Exception{
  LockOrder.requireOutsideTransaction();Snapshot snapshot=inspect(lease);boolean exists=objects.existsFinal(snapshot.key());
  if(exists){if(!queue.renew(lease))throw lost();snapshot=inspect(lease);if(snapshot.protectedCopy()){Snapshot captured=snapshot;return ()->cancel(lease,captured);}try{objects.deleteFinal(snapshot.key());}catch(Exception unavailable){/* The DELETE might already have committed. HEAD decides; no provider messages are persisted. */}if(objects.existsFinal(snapshot.key()))throw new java.io.IOException("CLEANUP_DELETE_UNCONFIRMED");}
  Snapshot captured=snapshot;return ()->finish(lease,captured);
 }
 private Snapshot inspect(JobQueue.Lease lease){return tx.execute(s->{
  requireLease(lease);UUID owner=Objects.requireNonNull(lease.userId());LockOrder.before(LockOrder.Rank.USER_SYNC,owner.toString());db.queryForMap("SELECT user_id FROM user_sync_state WHERE user_id=? FOR UPDATE",bytes(owner));
  var json=new tools.jackson.databind.json.JsonMapper().readTree(lease.payload());if(lease.type()!=JobQueue.Type.ASSET_DELETE || !"SERVER_COPY_CLEANUP".equals(json.path("kind").asText()) || !lease.aggregateId().toString().equals(json.path("cleanup_id").asText()))throw lost();UUID id=PinSlots.parse(json.path("recording_id").asText()),generation=PinSlots.parse(json.path("generation").asText());var key=new StorageObjectKeys.Final(owner,id,generation);String hash=json.path("sha256").asText();long authorized=json.path("deleting_revision").asLong();if(authorized<2)throw lost();
  LockOrder.before(LockOrder.Rank.RECORDING_ASSET,owner+"/"+id);var asset=db.queryForMap("SELECT cloud_state,object_key,generation,sha256,verified_size,cloud_revision FROM recording_asset WHERE user_id=? AND recording_id=? FOR UPDATE",bytes(owner),bytes(id));
  var rows=db.queryForList("SELECT generation,expected_sha256,expected_cloud_revision,state FROM cloud_cleanup WHERE user_id=? AND id=? AND recording_id=? FOR UPDATE",bytes(owner),bytes(lease.aggregateId()),bytes(id));if(rows.size()!=1)throw lost();var cleanup=rows.getFirst();
  if(!Set.of("DELETING","RETRY_WAIT").contains((String)cleanup.get("state")) || !Arrays.equals(bytes(generation),(byte[])cleanup.get("generation")) || !hash.equals(cleanup.get("expected_sha256")) || Math.addExact(((Number)cleanup.get("expected_cloud_revision")).longValue(),1)!=authorized || !"DELETING".equals(asset.get("cloud_state")) || !Arrays.equals(bytes(generation),(byte[])asset.get("generation")) || !hash.equals(asset.get("sha256")) || !key.value().equals(asset.get("object_key")) || ((Number)asset.get("cloud_revision")).longValue()<authorized)throw lost();
  if(db.queryForList("SELECT id FROM app_user WHERE id=? AND status='ACTIVE'",bytes(owner)).isEmpty())throw lost();boolean protectedCopy=CleanupProtection.mandatory(db,owner,id) || ((Number)asset.get("cloud_revision")).longValue()!=authorized;
  requireLease(lease);return new Snapshot(key,hash,((Number)asset.get("verified_size")).longValue(),((Number)asset.get("cloud_revision")).longValue(),protectedCopy);
 });}
 private void finish(JobQueue.Lease lease,Snapshot captured){
  lockAccounting(captured.key().owner());requireLease(lease);var current=asset(captured.key());validateIdentity(current,captured);long next=PinSlots.increment(((Number)current.get("cloud_revision")).longValue());var now=CleanupConfirmations.stamp(clock.instant());
  // The ledger and both counters commit together. Existing generation evidence must never debit again.
  if(!db.queryForList("SELECT id FROM deletion_ledger WHERE user_id=? AND entity_type='RECORDING_ASSET' AND entity_id=? AND object_generation=?",bytes(captured.key().owner()),bytes(captured.key().recording()),bytes(captured.key().generation())).isEmpty())throw new IllegalStateException("CLEANUP_LEDGER_REQUIRES_RECONCILIATION");
  db.update("INSERT INTO deletion_ledger(id,user_id,entity_type,entity_id,object_generation,revision,purged_at) VALUES(?,?,'RECORDING_ASSET',?,?,?,?)",bytes(UUID.randomUUID()),bytes(captured.key().owner()),bytes(captured.key().recording()),bytes(captured.key().generation()),next,now);
  if(db.update("UPDATE storage_usage SET used_bytes=used_bytes-?,revision=revision+1,updated_at=? WHERE user_id=? AND used_bytes>=?",captured.size(),now,bytes(captured.key().owner()),captured.size())!=1 || db.update("UPDATE global_storage_usage SET used_bytes=used_bytes-?,revision=revision+1,updated_at=? WHERE id=1 AND used_bytes>=?",captured.size(),now,captured.size())!=1)throw new IllegalStateException("CLEANUP_ACCOUNTING_MISMATCH");
  db.update("UPDATE recording_asset SET cloud_state='NONE',blocked_reason=NULL,object_key=NULL,generation=NULL,verified_size=NULL,sha256=NULL,stored_at=NULL,cloud_revision=?,updated_at=? WHERE user_id=? AND recording_id=?",next,now,bytes(captured.key().owner()),bytes(captured.key().recording()));
  completeState(lease,"SUCCEEDED",null,now);RetentionAssetEvents.publish(db,captured.key().owner(),captured.key().recording(),next,clock);
 }
 private void cancel(JobQueue.Lease lease,Snapshot captured){
  UUID owner=captured.key().owner(),id=captured.key().recording();LockOrder.before(LockOrder.Rank.USER_SYNC,owner.toString());db.queryForMap("SELECT user_id FROM user_sync_state WHERE user_id=? FOR UPDATE",bytes(owner));requireLease(lease);var current=asset(captured.key());validateIdentity(current,captured);long next=PinSlots.increment(((Number)current.get("cloud_revision")).longValue());var now=CleanupConfirmations.stamp(clock.instant());
  db.update("UPDATE recording_asset SET cloud_state='STORED',cloud_revision=?,updated_at=? WHERE user_id=? AND recording_id=?",next,now,bytes(owner),bytes(id));String reason=db.queryForList("SELECT id FROM recording WHERE user_id=? AND id=? AND song_id IS NULL",bytes(owner),bytes(id)).isEmpty()?"WAITING_LOCAL_CONFIRM":"ORPHAN_KEEP";
  if(db.queryForList("SELECT id FROM cloud_hold WHERE user_id=? AND recording_id=? AND reason=? AND related_operation_id IS NULL",bytes(owner),bytes(id),reason).isEmpty())db.update("INSERT INTO cloud_hold(id,user_id,recording_id,reason) VALUES(?,?,?,?)",bytes(UUID.randomUUID()),bytes(owner),bytes(id),reason);completeState(lease,"CANCELLED","PROTECTION_CHANGED",now);RetentionAssetEvents.publish(db,owner,id,next,clock);
 }
 private void completeState(JobQueue.Lease lease,String state,String error,LocalDateTime now){if(db.update("UPDATE cloud_cleanup SET state=?,error_code=?,lease_until=NULL,completed_at=?,updated_at=? WHERE user_id=? AND id=? AND state IN ('DELETING','RETRY_WAIT')",state,error,now,now,bytes(lease.userId()),bytes(lease.aggregateId()))!=1)throw lost();}
 public void retry(JobQueue.Lease lease){tx.executeWithoutResult(s->{if(!live(lease))return;UUID owner=lease.userId();LockOrder.before(LockOrder.Rank.USER_SYNC,owner.toString());db.queryForMap("SELECT user_id FROM user_sync_state WHERE user_id=? FOR UPDATE",bytes(owner));requireLease(lease);db.update("UPDATE cloud_cleanup SET state='RETRY_WAIT',error_code='OBJECT_RESULT_UNCONFIRMED',updated_at=? WHERE user_id=? AND id=? AND state IN ('DELETING','RETRY_WAIT')",CleanupConfirmations.stamp(clock.instant()),bytes(owner),bytes(lease.aggregateId()));});}
 private void lockAccounting(UUID owner){LockOrder.before(LockOrder.Rank.GLOBAL_STORAGE,"1");db.queryForMap("SELECT id FROM global_storage_usage WHERE id=1 FOR UPDATE");LockOrder.before(LockOrder.Rank.USER_SYNC,owner.toString());db.queryForMap("SELECT user_id FROM user_sync_state WHERE user_id=? FOR UPDATE",bytes(owner));LockOrder.before(LockOrder.Rank.STORAGE_USAGE,owner+"/");db.queryForMap("SELECT user_id FROM storage_usage WHERE user_id=? FOR UPDATE",bytes(owner));}
 private Map<String,Object> asset(StorageObjectKeys.Final key){LockOrder.before(LockOrder.Rank.RECORDING_ASSET,key.owner()+"/"+key.recording());return db.queryForMap("SELECT cloud_state,object_key,generation,sha256,verified_size,cloud_revision FROM recording_asset WHERE user_id=? AND recording_id=? FOR UPDATE",bytes(key.owner()),bytes(key.recording()));}
 private static void validateIdentity(Map<String,Object> current,Snapshot captured){if(!"DELETING".equals(current.get("cloud_state")) || !Arrays.equals(bytes(captured.key().generation()),(byte[])current.get("generation")) || !captured.hash().equals(current.get("sha256")) || !captured.key().value().equals(current.get("object_key")) || captured.size()!=((Number)current.get("verified_size")).longValue() || ((Number)current.get("cloud_revision")).longValue()<captured.revision())throw lost();}
 private boolean live(JobQueue.Lease lease){return lease.userId()!=null && lease.type()==JobQueue.Type.ASSET_DELETE && !db.queryForList("SELECT id FROM job WHERE id=? AND user_id=? AND aggregate_id=? AND type='ASSET_DELETE' AND state='RUNNING' AND lease_token=? AND lease_until>?",bytes(lease.id()),bytes(lease.userId()),bytes(lease.aggregateId()),bytes(lease.token()),CleanupConfirmations.stamp(clock.instant())).isEmpty();}
 private void requireLease(JobQueue.Lease lease){if(!live(lease))throw lost();}private static IllegalStateException lost(){return new IllegalStateException("CLEANUP_AUTHORITY_LOST");}
 private record Snapshot(StorageObjectKeys.Final key,String hash,long size,long revision,boolean protectedCopy){}
}
