package com.ksh321.songrecord.api.retention;
import java.util.*;import java.time.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;import org.springframework.transaction.TransactionDefinition;import com.ksh321.songrecord.api.locking.LockOrder;
import static com.ksh321.songrecord.api.songs.SongQueryKeys.*;
/** Pending/current transition primitives; no object deletion, quota bypass or automatic role removal. */
public final class PinTransitions {
 private final JdbcTemplate db;private final TransactionTemplate tx;private UUID cursorOwner;private int cursorSlot;
 public PinTransitions(JdbcTemplate db,PlatformTransactionManager manager){this.db=db;tx=new TransactionTemplate(manager);tx.setIsolationLevel(TransactionDefinition.ISOLATION_READ_COMMITTED);}
 public record Pending(int slot,UUID current,UUID target,long revision,UUID operation){}
 public static List<Pending> lockPending(JdbcTemplate db,UUID owner,UUID target,UUID operation){
  var numbers=db.queryForList("SELECT slot_no FROM pin_slot WHERE user_id=? AND pending_recording_id=? ORDER BY slot_no",Integer.class,bytes(owner),bytes(target));var result=new ArrayList<Pending>();
  for(int number:numbers){LockOrder.before(LockOrder.Rank.PIN_SLOT,owner+"/"+String.format(Locale.ROOT,"%010d",number));var rows=db.query("SELECT slot_no,current_recording_id,pending_recording_id,revision,operation_id FROM pin_slot WHERE user_id=? AND slot_no=? AND pending_recording_id=? FOR UPDATE",(r,n)->new Pending(r.getInt(1),PinSlots.id(r.getBytes(2)),uuid(r.getBytes(3)),r.getLong(4),PinSlots.id(r.getBytes(5))),bytes(owner),number,bytes(target));for(var row:rows)if(operation==null || operation.equals(row.operation()))result.add(row);}
  return result;
 }
 public static Map<UUID,List<Map<String,Object>>> lockAssets(JdbcTemplate db,UUID owner,List<Pending> slots,UUID target){
  var ids=new TreeSet<UUID>(Comparator.comparing(UUID::toString));ids.add(target);for(var slot:slots)if(slot.current()!=null)ids.add(slot.current());var result=new LinkedHashMap<UUID,List<Map<String,Object>>>();
  for(UUID id:ids){LockOrder.before(LockOrder.Rank.RECORDING_ASSET,owner+"/"+id);result.put(id,db.queryForList("SELECT cloud_state,cloud_revision,generation FROM recording_asset WHERE user_id=? AND recording_id=? FOR UPDATE",bytes(owner),bytes(id)));}return result;
 }
 public static void promoteLocked(JdbcTemplate db,UUID owner,List<Pending> slots,UUID target,Map<UUID,List<Map<String,Object>>> assets,boolean targetAdvanced,Clock clock){
  if(slots.isEmpty())return;if(db.queryForList("SELECT recording_id FROM recording_asset WHERE user_id=? AND recording_id=? AND cloud_state='STORED'",bytes(owner),bytes(target)).isEmpty() || db.queryForList("SELECT r.id FROM recording r JOIN app_user u ON u.id=r.user_id WHERE r.user_id=? AND r.id=? AND r.lifecycle_state='ACTIVE' AND r.metadata_state='SAVED' AND u.status='ACTIVE'",bytes(owner),bytes(target)).isEmpty())return;
  var affected=new HashSet<UUID>();for(var slot:slots){long next=PinSlots.increment(slot.revision());if(db.update("UPDATE pin_slot SET current_recording_id=?,pending_recording_id=NULL,revision=?,operation_id=NULL,requested_at=NULL,updated_at=? WHERE user_id=? AND slot_no=? AND revision=? AND pending_recording_id=?",bytes(target),next,CleanupConfirmations.stamp(clock.instant()),bytes(owner),slot.slot(),slot.revision(),bytes(target))!=1)throw new IllegalStateException("PIN_TRANSITION_CHANGED");if(slot.current()!=null)affected.add(slot.current());}
  if(!targetAdvanced)affected.add(target);bump(db,owner,affected,assets,clock);
 }
 private static void bump(JdbcTemplate db,UUID owner,Set<UUID> affected,Map<UUID,List<Map<String,Object>>> assets,Clock clock){for(UUID id:affected.stream().sorted(Comparator.comparing(UUID::toString)).toList()){var rows=assets.get(id);RetentionAssetVersions.bumpLocked(db,owner,id,rows);if(!rows.isEmpty())RetentionAssetEvents.publish(db,owner,id,PinSlots.increment(((Number)rows.getFirst().get("cloud_revision")).longValue()),clock);}}
 /** Captured upload request only. A stale upload cannot clear a later pending request. */
 public static void failedLocked(JdbcTemplate db,UUID owner,UUID target,UUID operation,Clock clock){if(operation==null)return;var slots=lockPending(db,owner,target,operation);slots=slots.stream().filter(x->x.current()!=null).toList();if(slots.isEmpty())return;var assets=lockAssets(db,owner,slots,target);clearLocked(db,owner,slots,assets,clock);}
 static void clearLocked(JdbcTemplate db,UUID owner,List<Pending> slots,Map<UUID,List<Map<String,Object>>> assets,Clock clock){var affected=new HashSet<UUID>();for(var slot:slots){if(db.update("UPDATE pin_slot SET pending_recording_id=NULL,revision=?,operation_id=NULL,requested_at=NULL,updated_at=? WHERE user_id=? AND slot_no=? AND revision=? AND pending_recording_id=?",PinSlots.increment(slot.revision()),CleanupConfirmations.stamp(clock.instant()),bytes(owner),slot.slot(),slot.revision(),bytes(slot.target()))!=1)throw new IllegalStateException("PIN_TRANSITION_CHANGED");affected.add(slot.target());if(slot.current()!=null)affected.add(slot.current());}bump(db,owner,affected,assets,clock);}
 public boolean finishStored(UUID owner,int slot){LockOrder.requireOutsideTransaction();return Boolean.TRUE.equals(tx.execute(s->{LockOrder.before(LockOrder.Rank.USER_SYNC,owner.toString());if(db.queryForList("SELECT user_id FROM user_sync_state WHERE user_id=? FOR UPDATE",bytes(owner)).isEmpty())return false;LockOrder.before(LockOrder.Rank.ENTITLEMENT,owner+"/");db.queryForList("SELECT user_id FROM user_entitlement WHERE user_id=? FOR UPDATE",bytes(owner));var targets=db.queryForList("SELECT pending_recording_id FROM pin_slot WHERE user_id=? AND slot_no=? AND pending_recording_id IS NOT NULL",byte[].class,bytes(owner),slot);if(targets.isEmpty())return false;UUID target=uuid(targets.getFirst());var pending=lockPending(db,owner,target,null);var assets=lockAssets(db,owner,pending,target);boolean stored=!assets.get(target).isEmpty() && "STORED".equals(assets.get(target).getFirst().get("cloud_state"));promoteLocked(db,owner,pending,target,assets,false,Clock.systemUTC());return stored && !pending.isEmpty() && db.queryForObject("SELECT COUNT(*) FROM pin_slot WHERE user_id=? AND slot_no=? AND current_recording_id=? AND pending_recording_id IS NULL",Long.class,bytes(owner),slot,bytes(target))==1;}));}
 public synchronized void refresh(){LockOrder.requireOutsideTransaction();var rows=cursorOwner==null?db.queryForList("SELECT p.user_id,p.slot_no FROM pin_slot p JOIN recording_asset a ON a.user_id=p.user_id AND a.recording_id=p.pending_recording_id WHERE a.cloud_state='STORED' ORDER BY p.user_id,p.slot_no LIMIT 100"):db.queryForList("SELECT p.user_id,p.slot_no FROM pin_slot p JOIN recording_asset a ON a.user_id=p.user_id AND a.recording_id=p.pending_recording_id WHERE a.cloud_state='STORED' AND (p.user_id>? OR (p.user_id=? AND p.slot_no>?)) ORDER BY p.user_id,p.slot_no LIMIT 100",bytes(cursorOwner),bytes(cursorOwner),cursorSlot);if(rows.isEmpty()){cursorOwner=null;cursorSlot=0;return;}for(var r:rows){cursorOwner=uuid((byte[])r.get("user_id"));cursorSlot=((Number)r.get("slot_no")).intValue();finishStored(cursorOwner,cursorSlot);}}
}
